import React from 'react';
import type { User, Story, Category, Business, Event, Deal, HeroSlide } from './types';
// FIX: Added 'Briefcase' to the import list from './components/icons' to make it available for use in this file.
import {
  Utensils, Coffee, ShoppingBag, Bed, Film, Music, Palette, Dumbbell, Car,
  Hospital, Landmark, Siren, Accessibility, Baby, Users2, Languages, Briefcase,
  Grid3x3
} from './components/icons';

// Mock User
export const mockUser: User = {
  name: 'Salar Ali',
  email: 'salar.ali@example.com',
  avatar: 'https://i.pravatar.cc/150?u=salarali',
};

// Hero Slides
export const heroSlides: HeroSlide[] = [
    {
        id: 1,
        title: "Discover Iraq's Hidden Gems",
        subtitle: "From the bustling markets of Baghdad to the serene landscapes of Kurdistan, find your next adventure.",
        image: "https://picsum.photos/seed/h1/1920/1080"
    },
    {
        id: 2,
        title: "Your Guide to Local Culture",
        subtitle: "Experience authentic Iraqi culture, cuisine, and hospitality with our curated guides and stories.",
        image: "https://picsum.photos/seed/h2/1920/1080"
    },
    {
        id: 3,
        title: "Connect with the Community",
        subtitle: "Join events, support local businesses, and share your experiences with a vibrant community.",
        image: "https://picsum.photos/seed/h3/1920/1080"
    }
];


// Stories
export const stories: Story[] = [
  { id: 1, avatar: 'https://i.pravatar.cc/150?u=a', name: 'Zahra', viewed: false, verified: true, thumbnail: 'https://picsum.photos/seed/s1/400/711', userName: 'Zahra Cooks', type: 'business', aiVerified: true, isLive: true, media: ['https://picsum.photos/seed/s1-1/1080/1920', 'https://picsum.photos/seed/s1-2/1080/1920'], timeAgo: '2h ago' },
  { id: 2, avatar: 'https://i.pravatar.cc/150?u=b', name: 'Ahmed', viewed: false, thumbnail: 'https://picsum.photos/seed/s2/400/711', userName: 'Baghdad Vibes', type: 'community', media: ['https://picsum.photos/seed/s2-1/1080/1920'], timeAgo: '5h ago' },
  { id: 3, avatar: 'https://i.pravatar.cc/150?u=c', name: 'Layla', viewed: true, verified: true, thumbnail: 'https://picsum.photos/seed/s3/400/711', userName: 'Erbil Boutique', type: 'business', media: ['https://picsum.photos/seed/s3-1/1080/1920'], timeAgo: '1d ago' },
  { id: 4, avatar: 'https://i.pravatar.cc/150?u=d', name: 'Yusuf', viewed: true, thumbnail: 'https://picsum.photos/seed/s4/400/711', userName: 'Kurdistan Hikes', type: 'community', aiVerified: true, media: ['https://picsum.photos/seed/s4-1/1080/1920', 'https://picsum.photos/seed/s4-2/1080/1920'], timeAgo: '1d ago' },
  { id: 5, avatar: 'https://i.pravatar.cc/150?u=e', name: 'Fatima', viewed: false, thumbnail: 'https://picsum.photos/seed/s5/400/711', userName: 'Basra Arts', type: 'community', media: ['https://picsum.photos/seed/s5-1/1080/1920'], timeAgo: '2d ago' },
];

// Categories
export const categories: Category[] = [
  { id: 'food_drink', icon: <Utensils />, nameKey: 'categories.food_drink', eventCount: 128, recommended: true,
    subcategories: [
      { id: 'restaurants', icon: <>🍴</>, nameKey: 'subcategories.dining_restaurants', subcategories: [
          { id: 'local_traditional', icon: <>🇮🇶</>, nameKey: 'subcategories.local_traditional', count: 40 },
          { id: 'international_cuisine', icon: <>🌍</>, nameKey: 'subcategories.international_cuisine', count: 25 },
          { id: 'fine_dining', icon: <>🥂</>, nameKey: 'subcategories.fine_dining', count: 10 },
          { id: 'casual_family', icon: <Users2 />, nameKey: 'subcategories.casual_family', count: 30 },
      ]},
      { id: 'cafes', icon: <Coffee />, nameKey: 'categories.cafes', subcategories: [
          { id: 'specialty_coffee', icon: <>☕</>, nameKey: 'subcategories.specialty_coffee', count: 30 },
          { id: 'traditional_tea_houses', icon: <>🫖</>, nameKey: 'subcategories.traditional_tea_houses', count: 13 },
          { id: 'dessert_pastry', icon: <>🍰</>, nameKey: 'subcategories.dessert_pastry', count: 22 },
      ]},
       { id: 'quick_service', icon: <>🥡</>, nameKey: 'subcategories.quick_service', subcategories: [
          { id: 'food_trucks', icon: <>🚚</>, nameKey: 'subcategories.food_trucks', count: 8 },
          { id: 'street_food', icon: <> Kebab</>, nameKey: 'subcategories.street_food', count: 18 },
      ]},
    ],
  },
  { id: 'shopping', icon: <ShoppingBag />, nameKey: 'categories.shopping', eventCount: 94,
    subcategories: [
        { id: 'retail_centers', icon: <>🏬</>, nameKey: 'subcategories.shopping_retail_centers', subcategories: [
            { id: 'shopping_malls', icon: <>🛍️</>, nameKey: 'subcategories.shopping_malls', count: 15 },
            { id: 'department_stores', icon: <>🏢</>, nameKey: 'subcategories.shopping_department_stores', count: 8 },
            { id: 'outlet_centers', icon: <>🏷️</>, nameKey: 'subcategories.shopping_outlet_centers', count: 5 },
        ]},
        { id: 'local_markets', icon: <>🛒</>, nameKey: 'subcategories.shopping_local_markets', subcategories: [
            { id: 'traditional_souqs', icon: <>🏺</>, nameKey: 'subcategories.shopping_traditional_souqs', count: 20 },
            { id: 'farmers_markets', icon: <>🥕</>, nameKey: 'subcategories.shopping_farmers_markets', count: 7 },
            { id: 'night_markets', icon: <>🌙</>, nameKey: 'subcategories.shopping_night_markets', count: 4 },
        ]},
        { id: 'specialty_shopping', icon: <>🎨</>, nameKey: 'subcategories.shopping_specialty', subcategories: [
            { id: 'handicrafts_artisans', icon: <>✋</>, nameKey: 'subcategories.shopping_handicrafts', count: 18 },
            { id: 'antiques_collectibles', icon: <>📜</>, nameKey: 'subcategories.shopping_antiques', count: 9 },
            { id: 'local_products', icon: <>🍯</>, nameKey: 'subcategories.shopping_local_products', count: 12 },
        ]},
        { id: 'services_repair', icon: <>🛠️</>, nameKey: 'subcategories.shopping_services_repair', subcategories: [
            { id: 'tailoring_alterations', icon: <>🧵</>, nameKey: 'subcategories.shopping_tailoring', count: 10 },
            { id: 'electronics_repair', icon: <>🔌</>, nameKey: 'subcategories.shopping_electronics_repair', count: 14 },
        ]},
    ]
  },
  { id: 'events_entertainment', icon: <Film />, nameKey: 'categories.events_entertainment', eventCount: 72, recommended: true,
    subcategories: [
      { id: 'live_performances', icon: <>🎵</>, nameKey: 'subcategories.live_performances', subcategories: [
          { id: 'music_concerts', icon: <Music />, nameKey: 'subcategories.music_concerts', count: 15 },
          { id: 'theater_drama', icon: <>🎭</>, nameKey: 'subcategories.theater_drama', count: 10 },
          { id: 'comedy_shows', icon: <>😂</>, nameKey: 'subcategories.comedy_shows', count: 8 },
      ]},
      { id: 'festivals_celebrations', icon: <>🎪</>, nameKey: 'subcategories.festivals_celebrations', subcategories: [
          { id: 'cultural_festivals', icon: <>🗿</>, nameKey: 'subcategories.cultural_festivals', count: 5 },
          // FIX: Replaced the undefined 'Users' icon with 'Users2', which is imported and available.
          { id: 'community_gatherings', icon: <Users2 />, nameKey: 'subcategories.community_gatherings', count: 12 },
      ]},
      { id: 'media_cinema', icon: <>🎬</>, nameKey: 'subcategories.media_cinema', subcategories: [
          { id: 'movie_theaters', icon: <Film />, nameKey: 'subcategories.movie_theaters', count: 25 },
          { id: 'gaming_centers', icon: <>🎮</>, nameKey: 'subcategories.gaming_centers', count: 18 },
      ]},
      { id: 'social_nightlife', icon: <>🍸</>, nameKey: 'subcategories.social_nightlife', subcategories: [
          { id: 'lounges_bars', icon: <> lounges_bars</>, nameKey: 'subcategories.lounges_bars', count: 20 },
          { id: 'hookah_cafes', icon: <>💨</>, nameKey: 'subcategories.hookah_cafes', count: 30 },
      ]},
    ]
   },
  { id: 'hotels_stays', icon: <Bed />, nameKey: 'categories.hotels_stays', eventCount: 56,
      subcategories: [
      { id: 'hotels_resorts', icon: <>🏙️</>, nameKey: 'subcategories.hotels_resorts', subcategories: [
          { id: 'luxury_5star', icon: <>💎</>, nameKey: 'subcategories.luxury_5star', count: 12 },
          { id: 'business_hotels', icon: <Briefcase />, nameKey: 'subcategories.business_hotels', count: 18 },
          { id: 'boutique_hotels', icon: <>🎨</>, nameKey: 'subcategories.boutique_hotels', count: 9 },
      ]},
      { id: 'alternative_stays', icon: <>🏡</>, nameKey: 'subcategories.alternative_stays', subcategories: [
          { id: 'guest_houses', icon: <>🏠</>, nameKey: 'subcategories.guest_houses', count: 25 },
          { id: 'hostels', icon: <> dormitory</>, nameKey: 'subcategories.hostels', count: 7 },
      ]},
      { id: 'business_extended', icon: <>💼</>, nameKey: 'subcategories.business_extended', subcategories: [
          { id: 'serviced_apartments', icon: <>🏢</>, nameKey: 'subcategories.serviced_apartments', count: 15 },
          { id: 'conference_hotels', icon: <>📈</>, nameKey: 'subcategories.conference_hotels', count: 6 },
      ]},
      { id: 'accessible_stays', icon: <Accessibility />, nameKey: 'subcategories.accessible_stays', subcategories: [
          { id: 'wheelchair_accessible_stays', icon: <Accessibility />, nameKey: 'subcategories.wheelchair_accessible_stays', count: 20 },
          { id: 'family_friendly_stays', icon: <Baby />, nameKey: 'subcategories.family_friendly_stays', count: 30 },
      ]},
    ]
  },
  { id: 'culture_heritage', icon: <Landmark />, nameKey: 'categories.culture_heritage', eventCount: 41, 
    subcategories: [
        { id: 'historical_sites', icon: <>🏛️</>, nameKey: 'subcategories.historical_sites', subcategories: [
            { id: 'archaeological_sites', icon: <>🏺</>, nameKey: 'subcategories.archaeological_sites', count: 10 },
            { id: 'historical_monuments', icon: <>🗿</>, nameKey: 'subcategories.historical_monuments', count: 15 },
            { id: 'unesco_heritage', icon: <>🌐</>, nameKey: 'subcategories.unesco_heritage', count: 4 },
        ]},
        { id: 'museums_galleries', icon: <>🎨</>, nameKey: 'subcategories.museums_galleries', subcategories: [
            { id: 'art_museums', icon: <>🖼️</>, nameKey: 'subcategories.art_museums', count: 8 },
            { id: 'historical_museums', icon: <>📜</>, nameKey: 'subcategories.historical_museums', count: 12 },
            { id: 'cultural_centers', icon: <>🏛️</>, nameKey: 'subcategories.cultural_centers', count: 9 },
        ]},
        { id: 'religious_sites', icon: <>🕌</>, nameKey: 'subcategories.religious_sites', subcategories: [
            { id: 'mosques', icon: <>🕌</>, nameKey: 'subcategories.mosques', count: 25 },
            { id: 'churches', icon: <>⛪</>, nameKey: 'subcategories.churches', count: 7 },
            { id: 'shrines', icon: <>🛐</>, nameKey: 'subcategories.shrines', count: 11 },
        ]},
        { id: 'public_spaces', icon: <>🌳</>, nameKey: 'subcategories.public_spaces', subcategories: [
            { id: 'parks_gardens', icon: <>🌳</>, nameKey: 'subcategories.parks_gardens', count: 18 },
            { id: 'public_squares', icon: <>🏞️</>, nameKey: 'subcategories.public_squares', count: 6 },
            { id: 'community_centers', icon: <Users2 />, nameKey: 'subcategories.community_centers', count: 9 },
        ]},
    ]
  },
  { id: 'business_services', icon: <Briefcase />, nameKey: 'categories.business_services', eventCount: 45,
    subcategories: [
      { id: 'financial_services', icon: <>🏦</>, nameKey: 'subcategories.financial_services', subcategories: [
        { id: 'banks', icon: <>🏦</>, nameKey: 'subcategories.banks', count: 20 },
        { id: 'currency_exchange', icon: <>💱</>, nameKey: 'subcategories.currency_exchange', count: 15 },
        { id: 'atms', icon: <>🏧</>, nameKey: 'subcategories.atms', count: 50 },
      ]},
      { id: 'communication', icon: <>📞</>, nameKey: 'subcategories.communication', subcategories: [
        { id: 'mobile_providers', icon: <>📱</>, nameKey: 'subcategories.mobile_providers', count: 5 },
        { id: 'internet_services', icon: <>🌐</>, nameKey: 'subcategories.internet_services', count: 10 },
        { id: 'postal_services', icon: <>📮</>, nameKey: 'subcategories.postal_services', count: 8 },
      ]},
      { id: 'professional_services', icon: <>🏢</>, nameKey: 'subcategories.professional_services', subcategories: [
        { id: 'legal_services', icon: <>⚖️</>, nameKey: 'subcategories.legal_services', count: 12 },
        { id: 'business_centers', icon: <>🏢</>, nameKey: 'subcategories.business_centers', count: 9 },
        { id: 'coworking_spaces', icon: <>🧑‍💻</>, nameKey: 'subcategories.coworking_spaces', count: 7 },
      ]},
      { id: 'educational_services', icon: <>🎓</>, nameKey: 'subcategories.educational_services', subcategories: [
        { id: 'tutoring_centers', icon: <>🧑‍🏫</>, nameKey: 'subcategories.tutoring_centers', count: 15 },
        { id: 'language_schools', icon: <>🗣️</>, nameKey: 'subcategories.language_schools', count: 11 },
        { id: 'vocational_training', icon: <>🔧</>, nameKey: 'subcategories.vocational_training', count: 8 },
      ]},
    ]
  },
  { id: 'health_wellness', icon: <Hospital />, nameKey: 'categories.health_wellness', eventCount: 35,
      subcategories: [
      { id: 'medical_services', icon: <>🏥</>, nameKey: 'subcategories.medical_services', subcategories: [
          { id: 'hospitals', icon: <Hospital />, nameKey: 'subcategories.hospitals', count: 15 },
          { id: 'clinics', icon: <>🩺</>, nameKey: 'subcategories.clinics', count: 25 },
          { id: 'emergency_care', icon: <Siren />, nameKey: 'subcategories.emergency_care', count: 10 },
      ]},
      { id: 'pharmacies_medicine', icon: <>💊</>, nameKey: 'subcategories.pharmacies_medicine', subcategories: [
          { id: 'pharmacies_24h', icon: <>🏪</>, nameKey: 'subcategories.pharmacies_24h', count: 20 },
          { id: 'medical_supplies', icon: <>🩹</>, nameKey: 'subcategories.medical_supplies', count: 12 },
      ]},
      { id: 'wellness_fitness', icon: <>🧘</>, nameKey: 'subcategories.wellness_fitness', subcategories: [
          { id: 'gyms_fitness', icon: <Dumbbell />, nameKey: 'subcategories.gyms_fitness', count: 30 },
          { id: 'yoga_meditation', icon: <>🧘‍♀️</>, nameKey: 'subcategories.yoga_meditation', count: 8 },
          { id: 'spas_wellness', icon: <>🧖</>, nameKey: 'subcategories.spas_wellness', count: 11 },
      ]},
      { id: 'family_health', icon: <Users2 />, nameKey: 'subcategories.family_health', subcategories: [
          { id: 'pediatric_care', icon: <Baby />, nameKey: 'subcategories.pediatric_care', count: 18 },
          { id: 'womens_health', icon: <>♀️</>, nameKey: 'subcategories.womens_health', count: 14 },
      ]},
    ]
  },
  { id: 'transport_mobility', icon: <Car />, nameKey: 'categories.transport_mobility', eventCount: 63, recommended: true,
    subcategories: [
        { id: 'local_transport', icon: <>🚕</>, nameKey: 'subcategories.local_transport', subcategories: [
            { id: 'taxi_services', icon: <>🚕</>, nameKey: 'subcategories.taxi_services', count: 25 },
            { id: 'ride_sharing', icon: <>🚗</>, nameKey: 'subcategories.ride_sharing', count: 10 },
            { id: 'public_buses', icon: <>🚌</>, nameKey: 'subcategories.public_buses', count: 15 },
        ]},
        { id: 'vehicle_services', icon: <>🔧</>, nameKey: 'subcategories.vehicle_services', subcategories: [
            { id: 'car_rentals', icon: <>🚙</>, nameKey: 'subcategories.car_rentals', count: 12 },
            { id: 'vehicle_repair', icon: <>🛠️</>, nameKey: 'subcategories.vehicle_repair', count: 20 },
            { id: 'fuel_stations', icon: <>⛽</>, nameKey: 'subcategories.fuel_stations', count: 40 },
        ]},
        { id: 'travel_services', icon: <>✈️</>, nameKey: 'subcategories.travel_services', subcategories: [
            { id: 'travel_agencies', icon: <>✈️</>, nameKey: 'subcategories.travel_agencies', count: 18 },
            { id: 'airline_offices', icon: <>🏢</>, nameKey: 'subcategories.airline_offices', count: 8 },
            { id: 'bus_terminals', icon: <>🚏</>, nameKey: 'subcategories.bus_terminals', count: 6 },
        ]},
        { id: 'accessible_transport', icon: <Accessibility />, nameKey: 'subcategories.accessible_transport', subcategories: [
            { id: 'wheelchair_accessible_transport', icon: <Accessibility />, nameKey: 'subcategories.wheelchair_accessible_transport', count: 9 },
            { id: 'senior_transport', icon: <>👴</>, nameKey: 'subcategories.senior_transport', count: 5 },
        ]},
    ]
  },
  { id: 'public_essential', icon: <Landmark />, nameKey: 'categories.public_essential', eventCount: 22,
    subcategories: [
      { id: 'government_services', icon: <>🏛️</>, nameKey: 'subcategories.public_government_services', subcategories: [
        { id: 'municipal_offices', icon: <>🏢</>, nameKey: 'subcategories.public_municipal_offices', count: 5 },
        { id: 'police_stations', icon: <Siren />, nameKey: 'subcategories.public_police_stations', count: 10 },
        { id: 'embassies_consulates', icon: <>🌍</>, nameKey: 'subcategories.public_embassies', count: 4 },
      ]},
      { id: 'emergency_services', icon: <>🚨</>, nameKey: 'subcategories.public_emergency_services', subcategories: [
        { id: 'emergency_numbers', icon: <>📞</>, nameKey: 'subcategories.public_emergency_numbers', count: 1 },
        { id: 'fire_departments', icon: <>🚒</>, nameKey: 'subcategories.public_fire_departments', count: 3 },
      ]},
      { id: 'community_services', icon: <>🌍</>, nameKey: 'subcategories.public_community_services', subcategories: [
        { id: 'community_centers', icon: <Users2 />, nameKey: 'subcategories.community_centers', count: 9 },
        { id: 'religious_centers', icon: <>🕌</>, nameKey: 'subcategories.religious_centers', count: 12 },
        { id: 'ngos_charities', icon: <>🤝</>, nameKey: 'subcategories.public_ngos', count: 6 },
      ]},
      { id: 'public_facilities', icon: <>🚻</>, nameKey: 'subcategories.public_facilities', subcategories: [
        { id: 'public_restrooms', icon: <>🚻</>, nameKey: 'subcategories.public_restrooms', count: 15 },
        { id: 'prayer_rooms', icon: <>🛐</>, nameKey: 'subcategories.public_prayer_rooms', count: 20 },
        { id: 'public_wifi', icon: <>📶</>, nameKey: 'subcategories.public_wifi', count: 8 },
      ]},
    ]
  },
];

// Businesses
export const businesses: Business[] = [
  { id: 1, name: 'Saj Al-Reef Restaurant', coverImage: 'https://picsum.photos/seed/b1/600/400', isPremium: true, category: 'food_drink', rating: 4.8, distance: 1.2, status: 'Open', image: 'https://picsum.photos/seed/b1/128/128', verified: true, reviews: 253 },
  { id: 2, name: 'Baghdad Mall', coverImage: 'https://picsum.photos/seed/b2/600/400', category: 'shopping', rating: 4.5, distance: 3.5, status: 'Open', image: 'https://picsum.photos/seed/b2/128/128', reviews: 512 },
  { id: 3, name: 'Divan Erbil Hotel', coverImage: 'https://picsum.photos/seed/b3/600/400', isPremium: true, category: 'hotels_stays', rating: 4.9, distance: 0.8, status: 'Open', image: 'https://picsum.photos/seed/b3/128/128', verified: true, reviews: 430 },
  { id: 4, name: 'Chai Khana', coverImage: 'https://picsum.photos/seed/b4/600/400', category: 'food_drink', rating: 4.6, distance: 2.1, status: 'Closes at 11 PM', image: 'https://picsum.photos/seed/b4/128/128', reviews: 189 },
  { id: 5, name: 'Iraq National Museum', coverImage: 'https://picsum.photos/seed/b5/600/400', category: 'culture_heritage', rating: 4.7, distance: 5.0, status: 'Open', image: 'https://picsum.photos/seed/b5/128/128', verified: true, reviews: 301 },
];

// Events
export const events: Event[] = [
  { id: 1, image: 'https://picsum.photos/seed/e1/600/400', title: 'Baghdad International Flower Festival', aiRecommended: true, date: new Date(new Date().setDate(new Date().getDate() + 3)), venue: 'Al-Zawraa Park, Baghdad', attendees: 1200, price: 0, accessibility: { wheelchairAccessible: true, familyFriendly: true } },
  { id: 2, image: 'https://picsum.photos/seed/e2/600/400', title: 'Kurdistan Tech Conference 2024', date: new Date(new Date().setDate(new Date().getDate() + 10)), venue: 'Erbil International Fair', attendees: 850, price: 25000, accessibility: { wheelchairAccessible: true, signLanguage: true } },
  { id: 3, image: 'https://picsum.photos/seed/e3/600/400', title: 'Traditional Iraqi Music Night', aiRecommended: true, date: new Date(new Date().setDate(new Date().getDate() + 5)), venue: 'Rashid Street, Baghdad', attendees: 300, price: 10000, accessibility: { audioDescription: true } },
  { id: 4, image: 'https://picsum.photos/seed/e4/600/400', title: 'Slemani International Book Fair', date: new Date(new Date().setDate(new Date().getDate() + 20)), venue: 'Slemani Expo Center', attendees: 5000, price: 5000, accessibility: { familyFriendly: true, wheelchairAccessible: true } },
  { id: 5, image: 'https://picsum.photos/seed/e5/600/400', title: 'Women in Business Networking Event', date: new Date(new Date().setDate(new Date().getDate() + 7)), venue: 'The Station, Baghdad', attendees: 150, price: 15000, accessibility: { womenOnly: true } },
  { id: 6, image: 'https://picsum.photos/seed/e6/600/400', title: 'Family Fun Day at the Park', date: new Date(new Date().setDate(new Date().getDate() + 2)), venue: 'Sami Abdulrahman Park, Erbil', attendees: 700, price: 0, accessibility: { familyFriendly: true, sensoryFriendly: true } },
];

// Deals
export const deals: Deal[] = [
  { id: 1, discount: 25, businessLogo: 'https://picsum.photos/seed/bl1/64/64', title: 'Off on All Main Courses', description: 'Enjoy a delicious discount at Zaytona Restaurant.', expiresIn: '3 Days', claimed: 78, total: 200 },
  { id: 2, discount: 50, businessLogo: 'https://picsum.photos/seed/bl2/64/64', title: 'Off Your First Month', description: 'Join Fitness World Gym and get half price.', expiresIn: '1 Week', claimed: 112, total: 150 },
  { id: 3, discount: 15, businessLogo: 'https://picsum.photos/seed/bl3/64/64', title: 'Off All Electronics', description: 'TechCity summer sale is here. Don\'t miss out!', expiresIn: '5 Days', claimed: 204, total: 500 },
];

// Governorates
export const governorates = [
    { id: 'all', nameKey: 'governorates.all' },
    { id: 'baghdad', nameKey: 'governorates.baghdad' },
    { id: 'basra', nameKey: 'governorates.basra' },
    { id: 'erbil', nameKey: 'governorates.erbil' },
    { id: 'sulaymaniyah', nameKey: 'governorates.sulaymaniyah' },
    { id: 'dohuk', nameKey: 'governorates.dohuk' },
    { id: 'nineveh', nameKey: 'governorates.nineveh' },
    { id: 'anbar', nameKey: 'governorates.anbar' },
    { id: 'babil', nameKey: 'governorates.babil' },
    { id: 'karbala', nameKey: 'governorates.karbala' },
    { id: 'najaf', nameKey: 'governorates.najaf' },
    { id: 'qadisiyyah', nameKey: 'governorates.qadisiyyah' },
    { id: 'wasit', nameKey: 'governorates.wasit' },
    { id: 'maysan', nameKey: 'governorates.maysan' },
    { id: 'dhi_qar', nameKey: 'governorates.dhi_qar' },
    { id: 'muthanna', nameKey: 'governorates.muthanna' },
    { id: 'diyala', nameKey: 'governorates.diyala' },
    { id: 'kirkuk', nameKey: 'governorates.kirkuk' },
    { id: 'salah_al_din', nameKey: 'governorates.salah_al_din' },
];

// Intl formatter
export const format = (date: Date, formatString: string) => {
    // A simple formatter for demonstration. 
    // In a real app, use a robust library like date-fns or moment.js.
    const options: Intl.DateTimeFormatOptions = {};
    if (formatString === 'd') options.day = 'numeric';
    if (formatString === 'MMM') options.month = 'short';
    if (formatString === 'h:mm a') {
        options.hour = 'numeric';
        options.minute = 'numeric';
        options.hour12 = true;
    }
    return new Intl.DateTimeFormat('en-US', options).format(date);
}

// Inclusive Features
export const inclusiveFeaturesList = [
    { key: 'accessibility', icon: <Accessibility className="w-8 h-8"/>, color: 'primary' },
    { key: 'family_friendly', icon: <Baby className="w-8 h-8"/>, color: 'secondary' },
    { key: 'women_only', icon: <Users2 className="w-8 h-8"/>, color: 'accent' },
    { key: 'multilingual_support', icon: <Languages className="w-8 h-8"/>, color: 'primary' },
];

// Translations
export const translations = {
  en: {
    items: "items",
    header: {
        signIn: "Sign In",
        dashboard: "Dashboard",
        logout: "Log Out",
        backToHome: "Back to Home",
    },
    hero: {
        searchPlaceholder: "Search for places, events, or services...",
        suggestionsTitle: "Popular Searches",
        filters: {
            eventsToday: "Events Today",
            restaurants: "Restaurants",
            entertainment: "Entertainment",
            deals: "Deals"
        }
    },
    stories: {
        add: "Add Yours",
        communityTitle: "Community Stories",
        business: "Business",
        community: "Community",
        addYours: "Add Yours",
        sendMessage: "Send message...",
    },
    filter: {
        governorate: "Filter by Governorate"
    },
    governorates: {
        all: "All Governorates",
        baghdad: "Baghdad",
        basra: "Basra",
        erbil: "Erbil",
        sulaymaniyah: "Sulaymaniyah",
        dohuk: "Dohuk",
        nineveh: "Nineveh",
        anbar: "Al Anbar",
        babil: "Babil",
        karbala: "Karbala",
        najaf: "Najaf",
        qadisiyyah: "Al-Qādisiyyah",
        wasit: "Wasit",
        maysan: "Maysan",
        dhi_qar: "Dhi Qar",
        muthanna: "Al Muthanna",
        diyala: "Diyala",
        kirkuk: "Kirkuk",
        salah_al_din: "Salah al-Din",
    },
    categories: {
        title: "Explore Categories",
        subtitle: "Find what you're looking for in your city.",
        events: "Events",
        food_drink: "Dining & Cuisine",
        restaurants: "Restaurants",
        cafes: "Cafés",
        shopping: "Shopping & Retail",
        events_entertainment: "Entertainment & Events",
        hotels_stays: "Accommodation & Stays",
        culture_heritage: "Culture & Heritage",
        business_services: "Business & Services",
        health_wellness: "Health & Wellness",
        transport_mobility: "Transport & Mobility",
        public_essential: "Public & Essential",
        education: "Education",
    },
    subcategories: {
        selectOne: "Select a subcategory",
        all: "All",
        // Dining
        dining_restaurants: "Restaurants",
        local_traditional: "Local & Traditional",
        international_cuisine: "International Cuisine",
        fine_dining: "Fine Dining",
        casual_family: "Casual & Family",
        specialty_coffee: "Specialty Coffee",
        traditional_tea_houses: "Traditional Tea Houses",
        dessert_pastry: "Dessert & Pastry",
        quick_service: "Quick Service",
        food_trucks: "Food Trucks",
        street_food: "Street Food",
        // Entertainment
        live_performances: "Live Performances",
        music_concerts: "Music Concerts",
        theater_drama: "Theater & Drama",
        comedy_shows: "Comedy Shows",
        festivals_celebrations: "Festivals & Celebrations",
        cultural_festivals: "Cultural Festivals",
        community_gatherings: "Community Gatherings",
        media_cinema: "Media & Cinema",
        movie_theaters: "Movie Theaters",
        gaming_centers: "Gaming Centers",
        social_nightlife: "Social & Nightlife",
        lounges_bars: "Lounges & Bars",
        hookah_cafes: "Hookah Cafes",
        // Shopping
        shopping_retail_centers: "Retail Centers",
        shopping_malls: "Shopping Malls",
        shopping_department_stores: "Department Stores",
        shopping_outlet_centers: "Outlet Centers",
        shopping_local_markets: "Local Markets",
        shopping_traditional_souqs: "Traditional Souqs",
        shopping_farmers_markets: "Farmers Markets",
        shopping_night_markets: "Night Markets",
        shopping_specialty: "Specialty Shopping",
        shopping_handicrafts: "Handicrafts & Artisans",
        shopping_antiques: "Antiques & Collectibles",
        shopping_local_products: "Local Products",
        shopping_services_repair: "Services & Repair",
        shopping_tailoring: "Tailoring & Alterations",
        shopping_electronics_repair: "Electronics Repair",
        // Accommodation
        hotels_resorts: "Hotels & Resorts",
        luxury_5star: "Luxury & 5-Star",
        business_hotels: "Business Hotels",
        boutique_hotels: "Boutique Hotels",
        alternative_stays: "Alternative Stays",
        guest_houses: "Guest Houses",
        hostels: "Hostels",
        business_extended: "Business & Extended",
        serviced_apartments: "Serviced Apartments",
        conference_hotels: "Conference Hotels",
        accessible_stays: "Accessible Stays",
        wheelchair_accessible_stays: "Wheelchair Accessible",
        family_friendly_stays: "Family-Friendly",
        // Culture & Heritage
        historical_sites: "Historical Sites",
        archaeological_sites: "Archaeological Sites",
        historical_monuments: "Historical Monuments",
        unesco_heritage: "UNESCO Heritage",
        ancient_ruins: "Ancient Ruins",
        museums_galleries: "Museums & Galleries",
        art_museums: "Art Museums",
        historical_museums: "Historical Museums",
        science_technology: "Science & Technology",
        cultural_centers: "Cultural Centers",
        learning_education: "Learning & Education",
        libraries: "Libraries",
        workshops_classes: "Workshops & Classes",
        cultural_tours: "Cultural Tours",
        educational_centers: "Educational Centers",
        religious_sites: "Religious Sites",
        mosques: "Mosques",
        churches: "Churches",
        shrines: "Shrines",
        religious_centers: "Religious Centers",
        public_spaces: "Public Spaces",
        parks_gardens: "Parks & Gardens",
        public_squares: "Public Squares",
        waterfronts: "Waterfronts",
        community_centers: "Community Centers",
        // Business & Services
        financial_services: "Financial Services",
        banks: "Banks",
        currency_exchange: "Currency Exchange",
        atms: "ATMs",
        communication: "Communication",
        mobile_providers: "Mobile Providers",
        internet_services: "Internet Services",
        postal_services: "Postal Services",
        professional_services: "Professional Services",
        legal_services: "Legal Services",
        business_centers: "Business Centers",
        coworking_spaces: "Co-working Spaces",
        educational_services: "Educational Services",
        tutoring_centers: "Tutoring Centers",
        language_schools: "Language Schools",
        vocational_training: "Vocational Training",
        // Health & Wellness
        medical_services: "Medical Services",
        hospitals: "Hospitals",
        clinics: "Clinics",
        emergency_care: "Emergency Care",
        pharmacies_medicine: "Pharmacies & Medicine",
        pharmacies_24h: "24-Hour Pharmacies",
        medical_supplies: "Medical Supplies",
        wellness_fitness: "Wellness & Fitness",
        gyms_fitness: "Gyms & Fitness Centers",
        yoga_meditation: "Yoga & Meditation",
        spas_wellness: "Spas & Wellness Centers",
        family_health: "Family Health",
        pediatric_care: "Pediatric Care",
        womens_health: "Women's Health",
        // Transport & Mobility
        local_transport: "Local Transport",
        taxi_services: "Taxi Services",
        ride_sharing: "Ride Sharing",
        public_buses: "Public Buses",
        vehicle_services: "Vehicle Services",
        car_rentals: "Car Rentals",
        vehicle_repair: "Vehicle Repair",
        fuel_stations: "Fuel Stations",
        travel_services: "Travel Services",
        travel_agencies: "Travel Agencies",
        airline_offices: "Airline Offices",
        bus_terminals: "Bus Terminals",
        accessible_transport: "Accessible Transport",
        wheelchair_accessible_transport: "Wheelchair Accessible",
        senior_transport: "Senior Transport",
        // Public & Essential
        public_government_services: "Government Services",
        public_municipal_offices: "Municipal Offices",
        public_police_stations: "Police Stations",
        public_embassies: "Embassies & Consulates",
        public_emergency_services: "Emergency Services",
        public_emergency_numbers: "Emergency Numbers",
        public_fire_departments: "Fire Departments",
        public_community_services: "Community Services",
        public_ngos: "NGOs & Charities",
        public_facilities: "Public Facilities",
        public_restrooms: "Public Restrooms",
        public_prayer_rooms: "Prayer Rooms",
        public_wifi: "Public Wi-Fi Zones",
    },
    featured: {
        title: "Featured Businesses",
        premium: "Premium"
    },
    actions: {
        book: "Book Now",
        details: "View Details"
    },
    events: {
        personalizedTitle: "Events, Personalized For You",
        tabs: {
            forYou: "For You",
            trending: "Trending",
            nearYou: "Near You",
            friendsGoing: "Friends Going"
        },
        aiPick: "AI Pick",
        going: "going",
        free: "FREE",
        viewDetails: "View Details",
    },
    deals: {
        title: "Deals Marketplace",
        expires: "Expires",
        claimed: "Claimed",
        claimNow: "Claim Now",
    },
    cityGuide: {
        title: "AI-Powered City Guide",
        planJourney: "Plan Your Journey",
        searchPlaces: "e.g., a one-day trip in Baghdad",
        generateJourney: "Generate",
        generating: "Generating...",
        trySaying: "Try saying",
        yourJourney: "Your Journey",
        addWaypoints: "Generate a journey to see your waypoints here.",
        startNavigation: "Start Navigation",
        generateError: "Sorry, I couldn't generate a journey. Please try again.",
    },
    directory: {
        title: "Business Directory",
        filters: "Filters",
        reset: "Reset",
        category: "Category",
        allCategories: "All Categories",
        minimumRating: "Minimum Rating",
        businessesFound: "businesses found",
        view: "View",
        contact: "Contact",
        viewProfile: "View Profile",
    },
    inclusive: {
        title: "A Platform For Everyone",
        subtitle: "We're committed to building an inclusive and accessible community for all of Iraq's diverse population.",
        findEvents: "Find Inclusive Events",
        eventsFound: "events found",
        noEventsFound: "No events match your selected filters.",
        filters: {
            wheelchairAccessible: "Wheelchair Accessible",
            familyFriendly: "Family Friendly",
            womenOnly: "Women Only",
            sensoryFriendly: "Sensory-Friendly",
            signLanguage: "Sign Language",
            audioDescription: "Audio Description",
        },
        features: {
            accessibility: {
                title: "Full Accessibility",
                description: "Find places with wheelchair access, ramps, and other essential facilities.",
            },
            family_friendly: {
                title: "Family-Friendly",
                description: "Discover events and locations that are safe and enjoyable for all ages.",
            },
            women_only: {
                title: "Women-Only Spaces",
                description: "Explore safe and exclusive spaces for women to connect and thrive.",
            },
            multilingual_support: {
                title: "Multilingual Support",
                description: "Navigate with ease with support for Arabic, Kurdish, and English.",
            },
        },
        visualAccessibility: {
            title: "Visual Accessibility",
            highContrast: "High Contrast Mode",
            highContrastDesc: "Increases text and background contrast for better readability.",
        },
        contrastChecker: {
            title: "Color Contrast Checker",
            textColor: "Text Color",
            bgColor: "Background Color",
            contrastRatio: "Contrast Ratio",
            compliance: "WCAG Compliance",
            pass: "Pass",
            fail: "Fail",
            normalText: "Normal Text",
            largeText: "Large Text (18pt+)",
            preview: "Preview",
            previewText: "This is some sample text.",
        }
    },
    auth: {
        signIn: "Sign In",
        signUp: "Sign Up",
        fullName: "Full Name",
        phone: "Phone Number",
        email: "Email Address",
        password: "Password",
        language: "Preferred Language",
        createAccount: "Create Account",
    },
    dashboard: {
        welcome: "Welcome",
        logout: "Log Out",
        profileSettings: "Profile Settings",
        saveChanges: "Save Changes",
        newPassword: "New Password",
        myFavorites: "My Favorites",
        recentActivity: "Recent Activity",
    },
    activity: {
        favorite: "Added to favorites",
        view: "Viewed event",
        search: "Searched for",
    }
  },
  ar: {
    items: "عناصر",
    header: {
        signIn: "تسجيل الدخول",
        dashboard: "لوحة التحكم",
        logout: "تسجيل الخروج",
        backToHome: "العودة للرئيسية",
    },
    hero: {
        searchPlaceholder: "ابحث عن أماكن، فعاليات، أو خدمات...",
        suggestionsTitle: "عمليات بحث رائجة",
        filters: {
            eventsToday: "فعاليات اليوم",
            restaurants: "مطاعم",
            entertainment: "ترفيه",
            deals: "عروض"
        }
    },
    stories: {
        add: "أضف قصتك",
        communityTitle: "قصص المجتمع",
        business: "عمل تجاري",
        community: "مجتمع",
        addYours: "أضف قصتك",
        sendMessage: "أرسل رسالة...",
    },
    filter: {
        governorate: "التصفية حسب المحافظة"
    },
    governorates: {
        all: "كل المحافظات",
        baghdad: "بغداد",
        basra: "البصرة",
        erbil: "أربيل",
        sulaymaniyah: "السليمانية",
        dohuk: "دهوك",
        nineveh: "نينوى",
        anbar: "الأنبار",
        babil: "بابل",
        karbala: "كربلاء",
        najaf: "النجف",
        qadisiyyah: "القادسية",
        wasit: "واسط",
        maysan: "ميسان",
        dhi_qar: "ذي قار",
        muthanna: "المثنى",
        diyala: "ديالى",
        kirkuk: "كركوك",
        salah_al_din: "صلاح الدين",
    },
    categories: {
        title: "استكشف الفئات",
        subtitle: "اعثر على ما تبحث عنه في مدينتك.",
        events: "فعاليات",
        food_drink: "الطعام والمأكولات",
        restaurants: "مطاعم",
        cafes: "مقاهي",
        shopping: "التسوق والتجزئة",
        events_entertainment: "الترفيه والفعاليات",
        hotels_stays: "الإقامة والفنادق",
        culture_heritage: "الثقافة والتراث",
        business_services: "الأعمال والخدمات",
        health_wellness: "الصحة والعافية",
        transport_mobility: "النقل والمواصلات",
        public_essential: "الخدمات العامة والأساسية",
        education: "تعليم",
    },
    subcategories: {
        selectOne: "اختر فئة فرعية",
        all: "الكل",
        // Dining
        dining_restaurants: "مطاعم",
        local_traditional: "محلي وتقليدي",
        international_cuisine: "مأكولات عالمية",
        fine_dining: "فاخر",
        casual_family: "عادي وعائلي",
        specialty_coffee: "قهوة مختصة",
        traditional_tea_houses: "بيوت شاي تقليدية",
        dessert_pastry: "حلويات ومعجنات",
        quick_service: "خدمة سريعة",
        food_trucks: "عربات طعام",
        street_food: "أكل الشارع",
        // Entertainment
        live_performances: "عروض حية",
        music_concerts: "حفلات موسيقية",
        theater_drama: "مسرح ودراما",
        comedy_shows: "عروض كوميدية",
        festivals_celebrations: "مهرجانات واحتفالات",
        cultural_festivals: "مهرجانات ثقافية",
        community_gatherings: "تجمعات مجتمعية",
        media_cinema: "إعلام وسينما",
        movie_theaters: "صالات سينما",
        gaming_centers: "مراكز ألعاب",
        social_nightlife: "حياة ليلية واجتماعية",
        lounges_bars: "استراحات وبارات",
        hookah_cafes: "مقاهي أركيلة",
        // Shopping
        shopping_retail_centers: "مراكز البيع بالتجزئة",
        shopping_malls: "مراكز التسوق",
        shopping_department_stores: "المتاجر الكبرى",
        shopping_outlet_centers: "مراكز الأوتلت",
        shopping_local_markets: "الأسواق المحلية",
        shopping_traditional_souqs: "الأسواق التقليدية",
        shopping_farmers_markets: "أسواق المزارعين",
        shopping_night_markets: "الأسواق الليلية",
        shopping_specialty: "تسوق متخصص",
        shopping_handicrafts: "الحرف اليدوية والفنانون",
        shopping_antiques: "التحف والمقتنيات",
        shopping_local_products: "المنتجات المحلية",
        shopping_services_repair: "الخدمات والتصليح",
        shopping_tailoring: "الخياطة والتعديلات",
        shopping_electronics_repair: "تصليح الإلكترونيات",
        // Accommodation
        hotels_resorts: "فنادق ومنتجعات",
        luxury_5star: "فخمة و 5 نجوم",
        business_hotels: "فنادق أعمال",
        boutique_hotels: "فنادق بوتيك",
        alternative_stays: "إقامات بديلة",
        guest_houses: "بيوت ضيافة",
        hostels: "نزل",
        business_extended: "إقامة طويلة وأعمال",
        serviced_apartments: "شقق فندقية",
        conference_hotels: "فنادق مؤتمرات",
        accessible_stays: "إقامات ميسرة",
        wheelchair_accessible_stays: "مجهزة للكراسي المتحركة",
        family_friendly_stays: "مناسبة للعائلات",
        // Culture & Heritage
        historical_sites: "المواقع التاريخية",
        archaeological_sites: "المواقع الأثرية",
        historical_monuments: "المعالم التاريخية",
        unesco_heritage: "تراث اليونسكو",
        ancient_ruins: "الآثار القديمة",
        museums_galleries: "المتاحف والمعارض",
        art_museums: "متاحف الفن",
        historical_museums: "المتاحف التاريخية",
        science_technology: "العلوم والتكنولوجيا",
        cultural_centers: "المراكز الثقافية",
        learning_education: "التعلم والتعليم",
        libraries: "المكتبات",
        workshops_classes: "ورش عمل ودروس",
        cultural_tours: "الجولات الثقافية",
        educational_centers: "المراكز التعليمية",
        religious_sites: "المواقع الدينية",
        mosques: "المساجد",
        churches: "الكنائس",
        shrines: "الأضرحة",
        religious_centers: "المراكز الدينية",
        public_spaces: "الأماكن العامة",
        parks_gardens: "الحدائق والمنتزهات",
        public_squares: "الساحات العامة",
        waterfronts: "الواجهات المائية",
        community_centers: "المراكز المجتمعية",
        // Business & Services
        financial_services: "الخدمات المالية",
        banks: "البنوك",
        currency_exchange: "صرافة العملات",
        atms: "أجهزة الصراف الآلي",
        communication: "الاتصالات",
        mobile_providers: "شركات الاتصالات",
        internet_services: "خدمات الإنترنت",
        postal_services: "الخدمات البريدية",
        professional_services: "الخدمات المهنية",
        legal_services: "الخدمات القانونية",
        business_centers: "مراكز الأعمال",
        coworking_spaces: "مساحات العمل المشتركة",
        educational_services: "الخدمات التعليمية",
        tutoring_centers: "مراكز الدروس الخصوصية",
        language_schools: "معاهد اللغات",
        vocational_training: "التدريب المهني",
        // Health & Wellness
        medical_services: "الخدمات الطبية",
        hospitals: "المستشفيات",
        clinics: "العيادات",
        emergency_care: "الرعاية الطارئة",
        pharmacies_medicine: "الصيدليات والأدوية",
        pharmacies_24h: "صيدليات 24 ساعة",
        medical_supplies: "المستلزمات الطبية",
        wellness_fitness: "العافية واللياقة البدنية",
        gyms_fitness: "الصالات الرياضية ومراكز اللياقة البدنية",
        yoga_meditation: "اليوغا والتأمل",
        spas_wellness: "المنتجعات الصحية ومراكز العافية",
        family_health: "صحة الأسرة",
        pediatric_care: "رعاية الأطفال",
        womens_health: "صحة المرأة",
        // Transport & Mobility
        local_transport: "النقل المحلي",
        taxi_services: "خدمات التاكسي",
        ride_sharing: "مشاركة الركوب",
        public_buses: "الحافلات العامة",
        vehicle_services: "خدمات المركبات",
        car_rentals: "تأجير السيارات",
        vehicle_repair: "تصليح المركبات",
        fuel_stations: "محطات الوقود",
        travel_services: "خدمات السفر",
        travel_agencies: "وكالات السفر",
        airline_offices: "مكاتب الطيران",
        bus_terminals: "محطات الحافلات",
        accessible_transport: "النقل الميسر",
        wheelchair_accessible_transport: "متاح للكراسي المتحركة",
        senior_transport: "نقل كبار السن",
        // Public & Essential
        public_government_services: "الخدمات الحكومية",
        public_municipal_offices: "الدوائر البلدية",
        public_police_stations: "مراكز الشرطة",
        public_embassies: "السفارات والقنصليات",
        public_emergency_services: "خدمات الطوارئ",
        public_emergency_numbers: "أرقام الطوارئ",
        public_fire_departments: "إدارات الإطفاء",
        public_community_services: "الخدمات المجتمعية",
        public_ngos: "المنظمات غير الحكومية والجمعيات الخيرية",
        public_facilities: "المرافق العامة",
        public_restrooms: "المراحيض العامة",
        public_prayer_rooms: "غرف الصلاة",
        public_wifi: "مناطق واي فاي عامة",
    },
    featured: {
        title: "أعمال تجارية مميزة",
        premium: "بريميوم"
    },
    actions: {
        book: "احجز الآن",
        details: "عرض التفاصيل"
    },
    events: {
        personalizedTitle: "فعاليات، مخصصة لك",
        tabs: {
            forYou: "لك",
            trending: "شائعة",
            nearYou: "بالقرب منك",
            friendsGoing: "الأصدقاء ذاهبون"
        },
        aiPick: "اختيار الذكاء الاصطناعي",
        going: "ذاهبون",
        free: "مجاني",
        viewDetails: "عرض التفاصيل",
    },
    deals: {
        title: "سوق العروض",
        expires: "ينتهي في",
        claimed: "تم الحصول عليها",
        claimNow: "احصل على العرض الآن",
    },
    cityGuide: {
        title: "دليل المدينة بالذكاء الاصطناعي",
        planJourney: "خطط لرحلتك",
        searchPlaces: "مثال: رحلة ليوم واحد في بغداد",
        generateJourney: "إنشاء",
        generating: "جاري الإنشاء...",
        trySaying: "جرّب أن تقول",
        yourJourney: "رحلتك",
        addWaypoints: "قم بإنشاء رحلة لرؤية نقاط طريقك هنا.",
        startNavigation: "ابدأ الملاحة",
        generateError: "عذراً، لم أتمكن من إنشاء رحلة. يرجى المحاولة مرة أخرى.",
    },
    directory: {
        title: "دليل الأعمال",
        filters: "فلاتر",
        reset: "إعادة تعيين",
        category: "الفئة",
        allCategories: "جميع الفئات",
        minimumRating: "أقل تقييم",
        businessesFound: "عمل تجاري موجود",
        view: "عرض",
        contact: "اتصال",
        viewProfile: "عرض الملف الشخصي",
    },
    inclusive: {
        title: "منصة للجميع",
        subtitle: "نحن ملتزمون ببناء مجتمع شامل ومتاح لجميع أطياف سكان العراق المتنوعين.",
        findEvents: "ابحث عن فعاليات شاملة",
        eventsFound: "فعاليات موجودة",
        noEventsFound: "لا توجد فعاليات تطابق الفلاتر المحددة.",
        filters: {
            wheelchairAccessible: "متاح للكراسي المتحركة",
            familyFriendly: "مناسب للعائلات",
            womenOnly: "للنساء فقط",
            sensoryFriendly: "مناسب للحساسية الحسية",
            signLanguage: "لغة الإشارة",
            audioDescription: "وصف صوتي",
        },
        features: {
            accessibility: {
                title: "إمكانية وصول كاملة",
                description: "اعثر على أماكن مزودة بوصول للكراسي المتحركة ومنحدرات ومرافق أساسية أخرى.",
            },
            family_friendly: {
                title: "مناسب للعائلة",
                description: "اكتشف الفعاليات والمواقع الآمنة والممتعة لجميع الأعمار.",
            },
            women_only: {
                title: "أماكن للنساء فقط",
                description: "استكشف مساحات آمنة وحصرية للنساء للتواصل والازدهار.",
            },
            multilingual_support: {
                title: "دعم متعدد اللغات",
                description: "تنقل بسهولة مع دعم اللغات العربية والكردية والإنجليزية.",
            },
        },
        visualAccessibility: {
            title: "إمكانية الوصول البصري",
            highContrast: "وضع التباين العالي",
            highContrastDesc: "يزيد من تباين النص والخلفية لتحسين قابلية القراءة.",
        },
        contrastChecker: {
            title: "مدقق تباين الألوان",
            textColor: "لون النص",
            bgColor: "لون الخلفية",
            contrastRatio: "نسبة التباين",
            compliance: "توافق WCAG",
            pass: "ناجح",
            fail: "فاشل",
            normalText: "نص عادي",
            largeText: "نص كبير (18pt+)",
            preview: "معاينة",
            previewText: "هذا نص تجريبي.",
        }
    },
    auth: {
        signIn: "تسجيل الدخول",
        signUp: "إنشاء حساب",
        fullName: "الاسم الكامل",
        phone: "رقم الهاتف",
        email: "البريد الإلكتروني",
        password: "كلمة المرور",
        language: "اللغة المفضلة",
        createAccount: "إنشاء حساب",
    },
    dashboard: {
        welcome: "أهلاً بك",
        logout: "تسجيل الخروج",
        profileSettings: "إعدادات الملف الشخصي",
        saveChanges: "حفظ التغييرات",
        newPassword: "كلمة مرور جديدة",
        myFavorites: "مفضلتي",
        recentActivity: "النشاط الأخير",
    },
    activity: {
        favorite: "أضيف إلى المفضلة",
        view: "تم عرض الفعالية",
        search: "تم البحث عن",
    }
  },
  ku: {
    items: "شتەکان",
    header: {
        signIn: "چوونەژوورەوە",
        dashboard: "داشبۆرد",
        logout: "چوونەدەرەوە",
        backToHome: "گەڕانەوە بۆ سەرەکی",
    },
    hero: {
        searchPlaceholder: "بگەڕێ بۆ شوێن، بۆنە، یان خزمەتگوزاری...",
        suggestionsTitle: "گەڕانە بەناوبانگەکان",
        filters: {
            eventsToday: "بۆنەکانی ئەمڕۆ",
            restaurants: "چێشتخانەکان",
            entertainment: "کات بەسەربردن",
            deals: "داشکانەکان"
        }
    },
    stories: {
        add: "هی خۆت زیاد بکە",
        communityTitle: "چیرۆکەکانی کۆمەڵگە",
        business: "بازرگانی",
        community: "کۆمەڵگە",
        addYours: "هی خۆت زیاد بکە",
        sendMessage: "نامە بنێرە...",
    },
    filter: {
        governorate: "فلتەرکردن بەپێی پارێزگا"
    },
    governorates: {
        all: "هەموو پارێزگاکان",
        baghdad: "بەغداد",
        basra: "بەسرە",
        erbil: "هەولێر",
        sulaymaniyah: "سلێمانی",
        dohuk: "دهۆک",
        nineveh: "نەینەوا",
        anbar: "ئەنبار",
        babil: "بابل",
        karbala: "کەربەلا",
        najaf: "نەجەف",
        qadisiyyah: "قادسیە",
        wasit: "واست",
        maysan: "میسان",
        dhi_qar: "زیقار",
        muthanna: "موسەننا",
        diyala: "دیالە",
        kirkuk: "کەرکوک",
        salah_al_din: "سەڵاحەدین",
    },
    categories: {
        title: "پۆلەکان بپشکنە",
        subtitle: "ئەوەی بەدوایدا دەگەڕێیت لە شارەکەتدا بیدۆزەرەوە.",
        events: "بۆنەکان",
        food_drink: "خواردن و خواردنەوە",
        restaurants: "چێشتخانەکان",
        cafes: "کافێکان",
        shopping: "بازاڕکردن و فرۆشتن",
        events_entertainment: "بۆنە و کات بەسەربردن",
        hotels_stays: "شوێنی مانەوە و هۆتێلەکان",
        culture_heritage: "کەلتوور و میرات",
        business_services: "کار و خزمەتگوزارییەکان",
        health_wellness: "تەندروستی و لەشجوانی",
        transport_mobility: "گواستنەوە و هاتووچۆ",
        public_essential: "خزمەتگوزارییە گشتی و گرنگەکان",
        education: "پەروەردە",
    },
    subcategories: {
        selectOne: "پۆلێکی لاوەکی هەڵبژێرە",
        all: "هەمووی",
        // Dining
        dining_restaurants: "چێشتخانەکان",
        local_traditional: "ناوخۆیی و truyềnëی",
        international_cuisine: "خواردنی نێودەوڵەتی",
        fine_dining: "خواردنی نایاب",
        casual_family: "ئاسایی و خێزانی",
        specialty_coffee: "قاوەی تایبەت",
        traditional_tea_houses: "چایخانە truyềnëییەکان",
        dessert_pastry: "شیرینی و هەویرکاری",
        quick_service: "خزمەتگوزاری خێرا",
        food_trucks: "ئۆتۆمبێلی خواردن",
        street_food: "خواردنی سەرشەقام",
        // Entertainment
        live_performances: "پێشکەشکردنی ڕاستەوخۆ",
        music_concerts: "کۆنسێرتی مۆسیقا",
        theater_drama: "شانۆ و دراما",
        comedy_shows: "پێشکەشکردنی کۆمیدی",
        festivals_celebrations: "فیستیڤاڵ و ئاهەنگەکان",
        cultural_festivals: "فیستیڤاڵە کەلتوورییەکان",
        community_gatherings: "کۆبوونەوەی کۆمەڵایەتی",
        media_cinema: "میدیا و سینەما",
        movie_theaters: "سینەماکان",
        gaming_centers: "ناوەندەکانی یاری",
        social_nightlife: "ژیانی شەوانە و کۆمەڵایەتی",
        lounges_bars: "لاونج و باڕەکان",
        hookah_cafes: "کافتریای نێرگەلە",
        // Shopping
        shopping_retail_centers: "ناوەندەکانی فرۆشتن",
        shopping_malls: "مۆڵەکان",
        shopping_department_stores: "فرۆشگا گەورەکان",
        shopping_outlet_centers: "ناوەندەکانی ئاوتلێت",
        shopping_local_markets: "بازاڕە ناوخۆییەکان",
        shopping_traditional_souqs: "بازاڕە truyềnëییەکان",
        shopping_farmers_markets: "بازاڕی جووتیاران",
        shopping_night_markets: "بازاڕە شەوانەکان",
        shopping_specialty: "بازاڕکردنی تایبەتمەند",
        shopping_handicrafts: "کاری دەستی و هونەرمەندان",
        shopping_antiques: "ئەنتیکە و کۆکراوەکان",
        shopping_local_products: "بەرهەمە ناوخۆییەکان",
        shopping_services_repair: "خزمەتگوزاری و چاککردنەوە",
        shopping_tailoring: "بەرگدرووی و دەستکاری",
        shopping_electronics_repair: "چاککردنەوەی ئەلیکترۆنیات",
        // Accommodation
        hotels_resorts: "هۆتێل و هاوینەهەوارەکان",
        luxury_5star: "لوکس و ٥ ئەستێرە",
        business_hotels: "هۆتێلی کار",
        boutique_hotels: "هۆتێلی بوتیک",
        alternative_stays: "شوێنی مانەوەی جێگرەوە",
        guest_houses: "میوانخانەکان",
        hostels: "هۆستێلەکان",
        business_extended: "کاری و مانەوەی درێژخایەن",
        serviced_apartments: "شووقەی خزمەتگوزاری",
        conference_hotels: "هۆتێلی کۆنفرانس",
        accessible_stays: "شوێنی مانەوەی گونجاو",
        wheelchair_accessible_stays: "گونجاو بۆ کورسی جووڵاو",
        family_friendly_stays: "گونجاو بۆ خێزان",
        // Culture & Heritage
        historical_sites: "شوێنە مێژووییەکان",
        archaeological_sites: "شوێنەوارەکان",
        historical_monuments: "شوێنەوارە مێژووییەکان",
        unesco_heritage: "میراتی یونسکۆ",
        ancient_ruins: "وێرانە کۆنەکان",
        museums_galleries: "مۆزەخانە و گالێریەکان",
        art_museums: "مۆزەخانەکانی هونەر",
        historical_museums: "مۆزەخانە مێژووییەکان",
        science_technology: "زانست و تەکنەلۆژیا",
        cultural_centers: "ناوەندە کەلتوورییەکان",
        learning_education: "فێربوون و پەروەردە",
        libraries: "کتێبخانەکان",
        workshops_classes: "ۆرکشۆپ و وانەکان",
        cultural_tours: "گەشتە کەلتوورییەکان",
        educational_centers: "ناوەندە پەروەردەییەکان",
        religious_sites: "شوێنە ئاینییەکان",
        mosques: "مزگەوتەکان",
        churches: "کڵێساکان",
        shrines: "مەزارگەکان",
        religious_centers: "ناوەندە ئاینییەکان",
        public_spaces: "شوێنە گشتییەکان",
        parks_gardens: "پارک و باخچەکان",
        public_squares: "گۆڕەپانە گشتییەکان",
        waterfronts: "کەنارئاوەکان",
        community_centers: "ناوەندە کۆمەڵایەتییەکان",
        // Business & Services
        financial_services: "خزمەتگوزارییە داراییەکان",
        banks: "بانکەکان",
        currency_exchange: "گۆڕینەوەی دراو",
        atms: "ئامێری پارە ڕاکێشان",
        communication: "پەیوەندی",
        mobile_providers: "کۆمپانیاکانی مۆبایل",
        internet_services: "خزمەتگوزاری ئینتەرنێت",
        postal_services: "خزمەتگوزاری پۆستە",
        professional_services: "خزمەتگوزارییە پیشەییەکان",
        legal_services: "خزمەتگوزاری یاسایی",
        business_centers: "ناوەندەکانی کار",
        coworking_spaces: "شوێنەکانی کاری هاوبەش",
        educational_services: "خزمەتگوزارییە پەروەردەییەکان",
        tutoring_centers: "ناوەندەکانی وانەوتنەوە",
        language_schools: "قوتابخانەکانی زمان",
        vocational_training: "ڕاهێنانی پیشەیی",
        // Health & Wellness
        medical_services: "خزمەتگوزارییە پزیشکییەکان",
        hospitals: "نەخۆشخانەکان",
        clinics: "کلینیکەکان",
        emergency_care: "فریاگوزاری خێرا",
        pharmacies_medicine: "دەرمانخانە و دەرمان",
        pharmacies_24h: "دەرمانخانەی ٢٤ کاتژمێری",
        medical_supplies: "پێداویستی پزیشکی",
        wellness_fitness: "لەشجوانی و تەندروستی",
        gyms_fitness: "هۆڵەکانی لەشجوانی",
        yoga_meditation: "یۆگا و медитаци",
        spas_wellness: "سپا و ناوەندەکانی تەندروستی",
        family_health: "تەندروستی خێزان",
        pediatric_care: "چاودێری منداڵان",
        womens_health: "تەندروستی ژنان",
        // Transport & Mobility
        local_transport: "گواستنەوەی ناوخۆیی",
        taxi_services: "خزمەتگوزاری تەکسی",
        ride_sharing: "هاوبەشیکردنی گەشت",
        public_buses: "پاسە گشتییەکان",
        vehicle_services: "خزمەتگوزاری ئۆتۆمبێل",
        car_rentals: "بەکرێدانی ئۆتۆمبێل",
        vehicle_repair: "چاککردنەوەی ئۆتۆمبێل",
        fuel_stations: "وێستگەکانی سووتەمەنی",
        travel_services: "خزمەتگوزارییەکانی گەشت",
        travel_agencies: "ئاژانسەکانی گەشتیاری",
        airline_offices: "نووسینگەکانی هێڵی ئاسمانی",
        bus_terminals: "تێرمیناڵی پاسەکان",
        accessible_transport: "گواستنەوەی گونجاو",
        wheelchair_accessible_transport: "گونجاو بۆ کورسی جووڵاو",
        senior_transport: "گواستنەوەی بەساڵاچووان",
        // Public & Essential
        public_government_services: "خزمەتگوزارییە حکومییەکان",
        public_municipal_offices: "فەرمانگە شارەوانییەکان",
        public_police_stations: "بنکەکانی پۆلیس",
        public_embassies: "باڵیۆزخانە و کونسوڵخانەکان",
        public_emergency_services: "خزمەتگوزارییەکانی فریاکەوتن",
        public_emergency_numbers: "ژمارەکانی فریاکەوتن",
        public_fire_departments: "بەڕێوەبەرایەتییەکانی ئاگرکوژێنەوە",
        public_community_services: "خزمەتگوزارییە کۆمەڵایەتییەکان",
        public_ngos: "ڕێکخراوە ناحکومییەکان و خێرخوازییەکان",
        public_facilities: "شوێنە گشتییەکان",
        public_restrooms: "توالێتە گشتییەکان",
        public_prayer_rooms: "ژوورەکانی نوێژ",
        public_wifi: "ناوچەکانی وای فای گشتی",
    },
    featured: {
        title: "کارە دیارەکان",
        premium: "پریمیۆم"
    },
    actions: {
        book: "ئێستا حیجز بکە",
        details: "پیشاندانی وردەکاری"
    },
    events: {
        personalizedTitle: "بۆنەکان، تایبەت بۆ تۆ",
        tabs: {
            forYou: "بۆ تۆ",
            trending: "تریند",
            nearYou: "نزیک تۆ",
            friendsGoing: "هاوڕێیان دەچن"
        },
        aiPick: "هەڵبژاردەی AI",
        going: "دەچن",
        free: "بێبەرامبەر",
        viewDetails: "بینینی وردەکارییەکان",
    },
    deals: {
        title: "بازاڕی داشکاندنەکان",
        expires: "کۆتایی دێت",
        claimed: "داواکراو",
        claimNow: "ئێستا داوای بکە",
    },
    cityGuide: {
        title: "ڕێبەری شار بە زیرەکی دەستکرد",
        planJourney: "پلانی گەشتەکەت دابنێ",
        searchPlaces: "نموونە: گەشتێکی یەک ڕۆژە لە بەغداد",
        generateJourney: "دروستکردن",
        generating: "دروست دەکرێت...",
        trySaying: "تاقی بکەوە بڵێیت",
        yourJourney: "گەشتەکەت",
        addWaypoints: "گەشتێک دروست بکە بۆ بینینی خاڵەکانی ڕێگاکەت لێرە.",
        startNavigation: "دەستپێکردنی ڕێدۆزی",
        generateError: "ببورە، نەمتوانی گەشتێک دروست بکەم. تکایە دووبارە هەوڵ بدەوە.",
    },
    directory: {
        title: "لیستی کارەکان",
        filters: "فلتەرەکان",
        reset: "سڕینەوە",
        category: "پۆل",
        allCategories: "هەموو پۆلەکان",
        minimumRating: "کەمترین هەڵسەنگاندن",
        businessesFound: "کار دۆزرایەوە",
        view: "بینین",
        contact: "پەیوەندی",
        viewProfile: "بینینی پرۆفایل",
    },
    inclusive: {
        title: "سەکۆیەک بۆ هەمووان",
        subtitle: "ئێمە پابەندین بە دروستکردنی کۆمەڵگەیەکی گشتگیر و دەستڕاگەیشتوو بۆ هەموو دانیشتوانە جیاوازەکانی عێراق.",
        findEvents: "دۆزینەوەی بۆنە گشتگیرەکان",
        eventsFound: "بۆنە دۆزرایەوە",
        noEventsFound: "هیچ بۆنەیەک نەدۆزرایەوە کە لەگەڵ فلتەرەکانت بگونجێت.",
        filters: {
            wheelchairAccessible: "گونجاو بۆ کورسی جووڵاو",
            familyFriendly: "گونجاو بۆ خێزان",
            womenOnly: "تەنها بۆ ژنان",
            sensoryFriendly: "گونجاو بۆ هەستیاری",
            signLanguage: "زمانی ئاماژە",
            audioDescription: "وەسفی دەنگی",
        },
        features: {
            accessibility: {
                title: "دەستڕاگەیشتنی تەواو",
                description: "شوێنەکان بدۆزەرەوە کە ڕێڕەوی کورسی جووڵاو و ئاسانکارییە بنەڕەتییەکانی تریان هەیە.",
            },
            family_friendly: {
                title: "دۆستی خێزان",
                description: "بۆنە و شوێنە سەلامەت و چێژبەخشەکان بۆ هەموو تەمەنەکان بدۆزەرەوە.",
            },
            women_only: {
                title: "شوێنی تایبەت بە ژنان",
                description: "شوێنە سەلامەت و تایبەتەکان بپشکنە بۆ ژنان بۆ پەیوەندی و گەشەکردن.",
            },
            multilingual_support: {
                title: "پشتیوانی فرەزمان",
                description: "بە ئاسانی بگەڕێ بە پشتیوانی زمانەکانی عەرەبی، کوردی، و ئینگلیزی.",
            },
        },
        visualAccessibility: {
            title: "دەستڕاگەیشتنی بینایی",
            highContrast: "دۆخی کۆنتراستی بەرز",
            highContrastDesc: "کۆنتراستی دەق و پاشبنەما زیاد دەکات بۆ خوێندنەوەی باشتر.",
        },
        contrastChecker: {
            title: "پشکنەری کۆنتراستی ڕەنگەکان",
            textColor: "ڕەنگی دەق",
            bgColor: "ڕەنگی پاشبنەما",
            contrastRatio: "ڕێژەی کۆنتراست",
            compliance: "گونجانی WCAG",
            pass: "سەرکەوتوو",
            fail: "سەرنەکەوتوو",
            normalText: "دەقی ئاسایی",
            largeText: "دەقی گەورە (18pt+)",
            preview: "پێشبینین",
            previewText: "ئەمە دەقێکی نموونەییە.",
        }
    },
    auth: {
        signIn: "چوونەژوورەوە",
        signUp: "هەژمار دروستکردن",
        fullName: "ناوی تەواو",
        phone: "ژمارەی تەلەفۆن",
        email: "ئیمەیڵ",
        password: "وشەی نهێنی",
        language: "زمانی دڵخواز",
        createAccount: "هەژمار دروست بکە",
    },
    dashboard: {
        welcome: "بەخێربێیت",
        logout: "چوونەدەرەوە",
        profileSettings: "ڕێکخستنەکانی پرۆفایل",
        saveChanges: "پاشەکەوتکردنی گۆڕانکارییەکان",
        newPassword: "وشەی نهێنی نوێ",
        myFavorites: "دڵخوازەکانم",
        recentActivity: "چالاکیەکانی دوایی",
    },
    activity: {
        favorite: "زیادکرا بۆ دڵخوازەکان",
        view: "بۆنەکە بینرا",
        search: "گەڕان کرا بۆ",
    }
  },
};
