import { CategoryInfo, CityInfo, Business, Review, Language } from './types';

export const CATEGORIES: CategoryInfo[] = [
  { id: 'restaurants', labelEn: 'Restaurants', labelAr: 'مطاعم', labelKu: 'چێشتخانەکان', emoji: '🍽️' },
  { id: 'cafes', labelEn: 'Cafes', labelAr: 'مقاهي', labelKu: 'کافێکان', emoji: '☕' },
  { id: 'hotels', labelEn: 'Hotels', labelAr: 'فنادق', labelKu: 'هوتێلەکان', emoji: '🏨' },
  { id: 'hospitals', labelEn: 'Hospitals', labelAr: 'مستشفيات', labelKu: 'نەخۆشخانەکان', emoji: '🏥' },
  { id: 'pharmacies', labelEn: 'Pharmacies', labelAr: 'صيدليات', labelKu: 'دەرمانخانەکان', emoji: '💊' },
  { id: 'shopping', labelEn: 'Shopping', labelAr: 'تسوق', labelKu: 'بازاڕکردن', emoji: '🛍️' },
  { id: 'education', labelEn: 'Education', labelAr: 'تعليم', labelKu: 'پەروەردە', emoji: '🎓' },
  { id: 'beauty', labelEn: 'Beauty', labelAr: 'تجميل', labelKu: 'جوانی', emoji: '💇' },
  { id: 'automotive', labelEn: 'Automotive', labelAr: 'سيارات', labelKu: 'ئۆتۆمبێل', emoji: '🚗' },
  { id: 'entertainment', labelEn: 'Entertainment', labelAr: 'ترفيه', labelKu: 'کات بەسەربردن', emoji: '🎭' },
  { id: 'sports', labelEn: 'Sports', labelAr: 'رياضة', labelKu: 'وەرزش', emoji: '⚽' },
  { id: 'services', labelEn: 'Services', labelAr: 'خدمات', labelKu: 'خزمەتگوزارییەکان', emoji: '🔧' },
];

export const GOVERNORATES = [
  'Baghdad', 'Basra', 'Nineveh', 'Erbil', 'Sulaymaniyah',
  'Duhok', 'Kirkuk', 'Anbar', 'Diyala', 'Babil', 'Karbala',
  'Najaf', 'Wasit', 'Maysan', 'Dhi Qar', 'Muthanna',
  'Qadisiyyah', 'Saladin'
];

export const CITIES: CityInfo[] = [
  { id: 'baghdad', nameEn: 'Baghdad', nameAr: 'بغداد', nameKu: 'بەغدا', governorate: 'Baghdad', emoji: '🕌' },
  { id: 'kadhimiyah', nameEn: 'Kadhimiyah', nameAr: 'الكاظمية', nameKu: 'کازمیە', governorate: 'Baghdad', emoji: '🕌' },
  { id: 'mansour', nameEn: 'Mansour', nameAr: 'المنصور', nameKu: 'مەنسوور', governorate: 'Baghdad', emoji: '🏙️' },
  { id: 'basra', nameEn: 'Basra', nameAr: 'البصرة', nameKu: 'بەسرە', governorate: 'Basra', emoji: '⚓' },
  { id: 'zubair', nameEn: 'Zubair', nameAr: 'الزبير', nameKu: 'زوبەیر', governorate: 'Basra', emoji: '🌴' },
  { id: 'qurna', nameEn: 'Qurna', nameAr: 'القرنة', nameKu: 'قوڕنە', governorate: 'Basra', emoji: '🌳' },
  { id: 'mosul', nameEn: 'Mosul', nameAr: 'الموصل', nameKu: 'مووسڵ', governorate: 'Nineveh', emoji: '🌉' },
  { id: 'tel-kaif', nameEn: 'Tel Kaif', nameAr: 'تلكيف', nameKu: 'تەلکێف', governorate: 'Nineveh', emoji: '🏘️' },
  { id: 'sinjar', nameEn: 'Sinjar', nameAr: 'سنجار', nameKu: 'شەنگال', governorate: 'Nineveh', emoji: '⛰️' },
  { id: 'erbil', nameEn: 'Erbil', nameAr: 'أربيل', nameKu: 'هەولێر', governorate: 'Erbil', emoji: '🏰' },
  { id: 'ankawa', nameEn: 'Ankawa', nameAr: 'عنكاوا', nameKu: 'عەنکاوە', governorate: 'Erbil', emoji: '⛪' },
  { id: 'soran', nameEn: 'Soran', nameAr: 'سوران', nameKu: 'سۆران', governorate: 'Erbil', emoji: '🏔️' },
  { id: 'sulaymaniyah', nameEn: 'Sulaymaniyah', nameAr: 'السليمانية', nameKu: 'سلێمانی', governorate: 'Sulaymaniyah', emoji: '⛰️' },
  { id: 'halabja', nameEn: 'Halabja', nameAr: 'حلبجة', nameKu: 'هەڵەبجە', governorate: 'Sulaymaniyah', emoji: '🌸' },
  { id: 'rania', nameEn: 'Rania', nameAr: 'رانية', nameKu: 'ڕانیە', governorate: 'Sulaymaniyah', emoji: '🌊' },
  { id: 'duhok', nameEn: 'Duhok', nameAr: 'دهوك', nameKu: 'دهۆک', governorate: 'Duhok', emoji: '🏞️' },
  { id: 'zakho', nameEn: 'Zakho', nameAr: 'زاخو', nameKu: 'زاخۆ', governorate: 'Duhok', emoji: '🌉' },
  { id: 'amadiyah', nameEn: 'Amadiyah', nameAr: 'العمادية', nameKu: 'ئامێدی', governorate: 'Duhok', emoji: '⛰️' },
  { id: 'kirkuk', nameEn: 'Kirkuk', nameAr: 'كركوك', nameKu: 'کەرکووک', governorate: 'Kirkuk', emoji: '🔥' },
  { id: 'hawija', nameEn: 'Hawija', nameAr: 'الحويجة', nameKu: 'حەویجە', governorate: 'Kirkuk', emoji: '🌾' },
  { id: 'daquq', nameEn: 'Daquq', nameAr: 'دقوق', nameKu: 'داقووق', governorate: 'Kirkuk', emoji: '🕌' },
  { id: 'ramadi', nameEn: 'Ramadi', nameAr: 'الرمادي', nameKu: 'ڕەمادی', governorate: 'Anbar', emoji: '🌅' },
  { id: 'fallujah', nameEn: 'Fallujah', nameAr: 'الفلوجة', nameKu: 'فەلووجە', governorate: 'Anbar', emoji: '🌉' },
  { id: 'hit', nameEn: 'Hit', nameAr: 'هيت', nameKu: 'هیت', governorate: 'Anbar', emoji: '🏰' },
  { id: 'baqubah', nameEn: 'Baqubah', nameAr: 'بعقوبة', nameKu: 'بەعقووبە', governorate: 'Diyala', emoji: '🍊' },
  { id: 'khanaqin', nameEn: 'Khanaqin', nameAr: 'خانقين', nameKu: 'خانەقین', governorate: 'Diyala', emoji: '🌉' },
  { id: 'muqdadiyah', nameEn: 'Muqdadiyah', nameAr: 'المقدادية', nameKu: 'شارەبان', governorate: 'Diyala', emoji: '🌳' },
  { id: 'hilla', nameEn: 'Hilla', nameAr: 'الحلة', nameKu: 'حلە', governorate: 'Babil', emoji: '🏛️' },
  { id: 'hashimiyah', nameEn: 'Hashimiyah', nameAr: 'الهاشمية', nameKu: 'هاشمیە', governorate: 'Babil', emoji: '🌾' },
  { id: 'mahayil', nameEn: 'Mahayil', nameAr: 'المحاويل', nameKu: 'مەحاویل', governorate: 'Babil', emoji: '🏛️' },
  { id: 'karbala', nameEn: 'Karbala', nameAr: 'كربلاء', nameKu: 'کەربەلا', governorate: 'Karbala', emoji: '🕌' },
  { id: 'hindiya', nameEn: 'Hindiya', nameAr: 'الهندية', nameKu: 'هیندیە', governorate: 'Karbala', emoji: '🌉' },
  { id: 'najaf', nameEn: 'Najaf', nameAr: 'النجف', nameKu: 'نەجەف', governorate: 'Najaf', emoji: '🕌' },
  { id: 'kufa', nameEn: 'Kufa', nameAr: 'الكوفة', nameKu: 'کووفە', governorate: 'Najaf', emoji: '🕌' },
  { id: 'kut', nameEn: 'Kut', nameAr: 'الكوت', nameKu: 'کووت', governorate: 'Wasit', emoji: '🌉' },
  { id: 'suwaira', nameEn: 'Suwaira', nameAr: 'الصويرة', nameKu: 'سوێرە', governorate: 'Wasit', emoji: '🌾' },
  { id: 'amara', nameEn: 'Amara', nameAr: 'العمارة', nameKu: 'عەمارە', governorate: 'Maysan', emoji: '🌊' },
  { id: 'maimouna', nameEn: 'Maimouna', nameAr: 'الميمونة', nameKu: 'مەیموونە', governorate: 'Maysan', emoji: '🌾' },
  { id: 'nasiriyah', nameEn: 'Nasiriyah', nameAr: 'الناصرية', nameKu: 'ناسریە', governorate: 'Dhi Qar', emoji: '🏺' },
  { id: 'shatra', nameEn: 'Shatra', nameAr: 'الشطرة', nameKu: 'شەترە', governorate: 'Dhi Qar', emoji: '🌾' },
  { id: 'samawah', nameEn: 'Samawah', nameAr: 'السماوة', nameKu: 'سەماوە', governorate: 'Muthanna', emoji: '🌵' },
  { id: 'rumaitha', nameEn: 'Rumaitha', nameAr: 'الرميثة', nameKu: 'ڕومەیسە', governorate: 'Muthanna', emoji: '🌾' },
  { id: 'diwaniyah', nameEn: 'Diwaniyah', nameAr: 'الديوانية', nameKu: 'دیوانیە', governorate: 'Qadisiyyah', emoji: '🐎' },
  { id: 'shamiya', nameEn: 'Shamiya', nameAr: 'الشامية', nameKu: 'شامیە', governorate: 'Qadisiyyah', emoji: '🌾' },
  { id: 'tikrit', nameEn: 'Tikrit', nameAr: 'تكريت', nameKu: 'تکریت', governorate: 'Saladin', emoji: '🏰' },
  { id: 'samarra', nameEn: 'Samarra', nameAr: 'سامراء', nameKu: 'سامەڕا', governorate: 'Saladin', emoji: '🕌' },
  { id: 'balad', nameEn: 'Balad', nameAr: 'بلد', nameKu: 'بەلەد', governorate: 'Saladin', emoji: '🍇' },
  { id: 'koya', nameEn: 'Koya', nameAr: 'كويسنجق', nameKu: 'کۆیە', governorate: 'Erbil', emoji: '🎓' },
  { id: 'dukan', nameEn: 'Dukan', nameAr: 'دوكان', nameKu: 'دووکان', governorate: 'Sulaymaniyah', emoji: '🌊' },
  { id: 'darbandikhan', nameEn: 'Darbandikhan', nameAr: 'دربندخان', nameKu: 'دەربەندیخان', governorate: 'Sulaymaniyah', emoji: '🏞️' },
  { id: 'akre', nameEn: 'Akre', nameAr: 'عقرة', nameKu: 'ئاکرێ', governorate: 'Duhok', emoji: '⛰️' },
  { id: 'sheikhan', nameEn: 'Sheikhan', nameAr: 'شيخان', nameKu: 'شێخان', governorate: 'Nineveh', emoji: '🕌' },
  { id: 'hamdaniya', nameEn: 'Hamdaniya', nameAr: 'الحمدانية', nameKu: 'حەمدانیە', governorate: 'Nineveh', emoji: '⛪' },
  { id: 'abu-ghraib', nameEn: 'Abu Ghraib', nameAr: 'أبو غريب', nameKu: 'ئەبوو غرێب', governorate: 'Baghdad', emoji: '🌾' },
  { id: 'mahmudiyah', nameEn: 'Mahmudiyah', nameAr: 'المحمودية', nameKu: 'مەحموودیە', governorate: 'Baghdad', emoji: '🌾' },
  { id: 'taji', nameEn: 'Taji', nameAr: 'التاجي', nameKu: 'تاجی', governorate: 'Baghdad', emoji: '🏭' },
  { id: 'fao', nameEn: 'Fao', nameAr: 'الفاو', nameKu: 'فاو', governorate: 'Basra', emoji: '⚓' },
  { id: 'um-qasr', nameEn: 'Um Qasr', nameAr: 'أم قصر', nameKu: 'ئوم قەسر', governorate: 'Basra', emoji: '🚢' },
  { id: 'haditha', nameEn: 'Haditha', nameAr: 'حديثة', nameKu: 'حەدیسە', governorate: 'Anbar', emoji: '🌊' },
  { id: 'ana', nameEn: 'Ana', nameAr: 'عنة', nameKu: 'عانە', governorate: 'Anbar', emoji: '🏞️' },
  { id: 'rutba', nameEn: 'Rutba', nameAr: 'الرطبة', nameKu: 'ڕوتبە', governorate: 'Anbar', emoji: '🌵' },
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: '1',
    name: 'Rotana Erbil Hotel',
    nameAr: 'فندق روتانا أربيل',
    nameKu: 'هوتێلی رۆتانا هەولێر',
    category: 'hotels',
    governorate: 'Erbil',
    city: 'Erbil',
    address: 'Gulan Street, Erbil',
    phone: '+964 66 210 5555',
    description: 'A luxury 5-star hotel located in the heart of Erbil, offering world-class amenities and service.',
    descriptionAr: 'فندق فاخر 5 نجوم يقع في قلب أربيل، يقدم مرافق وخدمات عالمية المستوى.',
    descriptionKu: 'هوتێلێکی لوکس ٥ ئەستێرە کە لە دڵی هەولێر هەڵکەوتووە، ئاسانکاری و خزمەتگوزاری ئاستی جیهانی پێشکەش دەکات.',
    rating: 4.8,
    reviewCount: 1250,
    isVerified: true,
    isFeatured: true,
    tags: ['luxury', 'pool', 'spa', 'business'],
    priceRange: 4,
    openHours: '24/7'
  },
  {
    id: '2',
    name: 'Al-Rasheed Restaurant',
    nameAr: 'مطعم الرشيد',
    nameKu: 'چێشتخانەی ڕەشید',
    category: 'restaurants',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Al-Mansour, Baghdad',
    phone: '+964 780 123 4567',
    description: 'Traditional Iraqi cuisine served in an elegant atmosphere. Famous for Masgouf.',
    descriptionAr: 'مأكولات عراقية تقليدية تقدم في أجواء راقية. مشهور بالمسكوف.',
    descriptionKu: 'خواردنی نەریتی عێراقی کە لە کەشێکی ڕاقیدا پێشکەش دەکرێت. بە مەسگوف بەناوبانگە.',
    rating: 4.5,
    reviewCount: 850,
    isVerified: true,
    isFeatured: true,
    tags: ['traditional', 'masgouf', 'family'],
    priceRange: 3,
    openHours: '12:00 PM - 12:00 AM'
  },
  {
    id: '3',
    name: 'Kurdistan Mall',
    nameAr: 'كوردستان مول',
    nameKu: 'کوردستان مۆڵ',
    category: 'shopping',
    governorate: 'Erbil',
    city: 'Erbil',
    address: '100m Road, Erbil',
    description: 'One of the largest shopping malls in Erbil with international brands and a food court.',
    descriptionAr: 'واحد من أكبر مراكز التسوق في أربيل مع علامات تجارية عالمية وساحة طعام.',
    descriptionKu: 'یەکێک لە گەورەترین مۆڵەکانی بازاڕکردن لە هەولێر بە براندە نێودەوڵەتییەکان و گۆڕەپانی خواردن.',
    rating: 4.6,
    reviewCount: 2100,
    isVerified: true,
    isFeatured: true,
    tags: ['shopping', 'brands', 'cinema'],
    priceRange: 3,
    openHours: '10:00 AM - 11:00 PM'
  },
  {
    id: '4',
    name: 'Divan Cafe',
    nameAr: 'ديوان كافيه',
    nameKu: 'دیوان کافێ',
    category: 'cafes',
    governorate: 'Sulaymaniyah',
    city: 'Sulaymaniyah',
    address: 'Salim Street, Sulaymaniyah',
    description: 'Cozy cafe with a great selection of coffee and desserts. Perfect for studying or meetings.',
    descriptionAr: 'مقهى مريح مع مجموعة رائعة من القهوة والحلويات. مثالي للدراسة أو الاجتماعات.',
    descriptionKu: 'کافێیەکی ئارام بە هەڵبژاردەیەکی زۆری قاوە و شیرینی. گونجاوە بۆ خوێندن یان کۆبوونەوە.',
    rating: 4.7,
    reviewCount: 420,
    isVerified: false,
    isFeatured: false,
    tags: ['coffee', 'wifi', 'desserts'],
    priceRange: 2,
    openHours: '8:00 AM - 12:00 AM'
  },
  {
    id: '5',
    name: 'Ibn Sina Hospital',
    nameAr: 'مستشفى ابن سينا',
    nameKu: 'نەخۆشخانەی ئیبن سینا',
    category: 'hospitals',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'International Zone, Baghdad',
    description: 'A leading medical facility providing specialized healthcare services.',
    descriptionAr: 'منشأة طبية رائدة تقدم خدمات رعاية صحية متخصصة.',
    descriptionKu: 'دامەزراوەیەکی پزیشکی پێشەنگ کە خزمەتگوزارییە تەندروستییە پسپۆڕییەکان پێشکەش دەکات.',
    rating: 4.9,
    reviewCount: 150,
    isVerified: true,
    isFeatured: false,
    tags: ['medical', 'emergency', 'specialized'],
    priceRange: 3,
    openHours: '24/7'
  },
  {
    id: '6',
    name: 'Basra International Hotel',
    nameAr: 'فندق البصرة الدولي',
    nameKu: 'هۆتێلی نێودەوڵەتی بەسرە',
    category: 'hotels',
    governorate: 'Basra',
    city: 'Basra',
    address: 'Corniche Street, Basra',
    description: 'Iconic hotel overlooking the Shatt al-Arab river.',
    descriptionAr: 'فندق أيقوني يطل على شط العرب.',
    descriptionKu: 'هۆتێلێکی ئایکۆنی کە دەڕوانێتە سەر ڕووباری شەتلعەرەب.',
    rating: 4.3,
    reviewCount: 600,
    isVerified: true,
    isFeatured: false,
    tags: ['river-view', 'historic', 'business'],
    priceRange: 3,
    openHours: '24/7'
  },
  {
    id: '7',
    name: 'Babylon Mall',
    nameAr: 'بابل مول',
    nameKu: 'بابیلۆن مۆڵ',
    category: 'shopping',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Al-Mansour, Baghdad',
    description: 'Modern shopping destination with a wide variety of shops and entertainment.',
    descriptionAr: 'وجهة تسوق حديثة مع مجموعة واسعة من المحلات والترفيه.',
    descriptionKu: 'شوێنی بازاڕکردنی مۆدێرن بە جۆرەها دوکان و کات بەسەربردن.',
    rating: 4.5,
    reviewCount: 1800,
    isVerified: true,
    isFeatured: true,
    tags: ['shopping', 'entertainment', 'food-court'],
    priceRange: 3,
    openHours: '10:00 AM - 11:00 PM'
  },
  {
    id: '8',
    name: 'Saj Al-Reef',
    nameAr: 'صاج الريف',
    nameKu: 'ساجی ڕیف',
    category: 'restaurants',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Zayouna, Baghdad',
    description: 'Popular fast food chain known for its delicious saj sandwiches.',
    descriptionAr: 'سلسلة مطاعم وجبات سريعة مشهورة بسندويشات الصاج اللذيذة.',
    descriptionKu: 'زنجیرە چێشتخانەیەکی خواردنی خێرای بەناوبانگە کە بە سەندویچە بەتامەکانی ساج ناسراوە.',
    rating: 4.2,
    reviewCount: 2500,
    isVerified: true,
    isFeatured: false,
    tags: ['fast-food', 'saj', 'affordable'],
    priceRange: 2,
    openHours: '11:00 AM - 1:00 AM'
  },
  {
    id: '9',
    name: 'Family Mall Erbil',
    nameAr: 'فاميلي مول أربيل',
    nameKu: 'فامیلی مۆڵ هەولێر',
    category: 'shopping',
    governorate: 'Erbil',
    city: 'Erbil',
    address: '100m Road, Erbil',
    description: 'Premier shopping and entertainment destination in Erbil.',
    descriptionAr: 'وجهة التسوق والترفيه الأولى في أربيل.',
    descriptionKu: 'شوێنی یەکەمی بازاڕکردن و کات بەسەربردن لە هەولێر.',
    rating: 4.7,
    reviewCount: 3500,
    isVerified: true,
    isFeatured: true,
    tags: ['shopping', 'cinema', 'family'],
    priceRange: 3,
    openHours: '10:00 AM - 12:00 AM'
  },
  {
    id: '10',
    name: 'Chavi Land',
    nameAr: 'چاوي لاند',
    nameKu: 'چاڤی لاند',
    category: 'entertainment',
    governorate: 'Sulaymaniyah',
    city: 'Sulaymaniyah',
    address: 'Goizha Mountain, Sulaymaniyah',
    description: 'Large amusement park with stunning views of the city.',
    descriptionAr: 'مدينة ملاهي كبيرة مع إطلالات خلابة على المدينة.',
    descriptionKu: 'پارکێکی گەورەی کات بەسەربردن بە دیمەنە سەرنجڕاکێشەکانی شارەکە.',
    rating: 4.4,
    reviewCount: 2200,
    isVerified: true,
    isFeatured: true,
    tags: ['park', 'view', 'family'],
    priceRange: 2,
    openHours: '2:00 PM - 12:00 AM'
  },
  {
    id: '11',
    name: 'Grand Millennium Sulaimani',
    nameAr: 'فندق جراند ميلينيوم السليمانية',
    nameKu: 'هۆتێلی گراند میلینیۆم سلێمانی',
    category: 'hotels',
    governorate: 'Sulaymaniyah',
    city: 'Sulaymaniyah',
    address: 'Bakhtiary, Sulaymaniyah',
    description: 'Luxury landmark hotel with a revolving restaurant.',
    descriptionAr: 'فندق فاخر ومعلم بارز مع مطعم دوار.',
    descriptionKu: 'هۆتێلێکی لوکس و نیشانەیەکی دیار بە چێشتخانەیەکی خولاوە.',
    rating: 4.8,
    reviewCount: 950,
    isVerified: true,
    isFeatured: true,
    tags: ['luxury', 'view', 'landmark'],
    priceRange: 4,
    openHours: '24/7'
  },
  {
    id: '12',
    name: 'Ziggurat of Ur',
    nameAr: 'زقورة أور',
    nameKu: 'زیگوراتی ئور',
    category: 'entertainment',
    governorate: 'Dhi Qar',
    city: 'Nasiriyah',
    address: 'Ur Archaeological Site',
    description: 'Ancient Sumerian ziggurat dating back to the Early Bronze Age.',
    descriptionAr: 'زقورة سومرية قديمة تعود إلى العصر البرونزي المبكر.',
    descriptionKu: 'زیگوراتی سۆمەری کۆن کە مێژووەکەی دەگەڕێتەوە بۆ سەرەتای سەردەمی برۆنز.',
    rating: 4.9,
    reviewCount: 1200,
    isVerified: true,
    isFeatured: true,
    tags: ['historic', 'archaeology', 'landmark'],
    priceRange: 1,
    openHours: '8:00 AM - 5:00 PM'
  },
  {
    id: '13',
    name: 'Al-Shaheed Monument',
    nameAr: 'نصب الشهيد',
    nameKu: 'مۆنۆمێنتی شەهید',
    category: 'entertainment',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Palestine Street, Baghdad',
    description: 'Iconic monument dedicated to the Iraqi soldiers who died in the Iran-Iraq War.',
    descriptionAr: 'نصب تذكاري أيقوني مخصص للجنود العراقيين الذين استشهدوا في الحرب العراقية الإيرانية.',
    descriptionKu: 'مۆنۆمێنتێکی ئایکۆنی کە تەرخانکراوە بۆ ئەو سەربازە عێراقییانەی لە شەڕی عێراق و ئێراندا گیانیان لەدەستداوە.',
    rating: 4.7,
    reviewCount: 3000,
    isVerified: true,
    isFeatured: false,
    tags: ['monument', 'historic', 'landmark'],
    priceRange: 1,
    openHours: '9:00 AM - 6:00 PM'
  },
  {
    id: '14',
    name: 'University of Baghdad',
    nameAr: 'جامعة بغداد',
    nameKu: 'زانکۆی بەغدا',
    category: 'education',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Al-Jadriya, Baghdad',
    description: 'The largest and oldest university in Iraq.',
    descriptionAr: 'أكبر وأقدم جامعة في العراق.',
    descriptionKu: 'گەورەترین و کۆنترین زانکۆ لە عێراق.',
    rating: 4.5,
    reviewCount: 500,
    isVerified: true,
    isFeatured: false,
    tags: ['university', 'education', 'historic'],
    priceRange: 1,
    openHours: '8:00 AM - 4:00 PM'
  },
  {
    id: '15',
    name: 'Dream City',
    nameAr: 'دريم سيتي',
    nameKu: 'دریم سیتی',
    category: 'entertainment',
    governorate: 'Duhok',
    city: 'Duhok',
    address: 'Duhok, Iraq',
    description: 'Modern amusement park for families and children.',
    descriptionAr: 'مدينة ملاهي حديثة للعائلات والأطفال.',
    descriptionKu: 'پارکێکی کات بەسەربردنی مۆدێرن بۆ خێزان و منداڵان.',
    rating: 4.3,
    reviewCount: 800,
    isVerified: true,
    isFeatured: false,
    tags: ['park', 'family', 'kids'],
    priceRange: 2,
    openHours: '4:00 PM - 11:00 PM'
  },
  {
    id: '16',
    name: 'Al-Mansour Mall',
    nameAr: 'المنصور مول',
    nameKu: 'مۆڵی مەنسوور',
    category: 'shopping',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Al-Mansour, Baghdad',
    description: 'One of the most popular shopping destinations in Baghdad.',
    descriptionAr: 'واحد من أشهر وجهات التسوق في بغداد.',
    descriptionKu: 'یەکێک لە بەناوبانگترین شوێنەکانی بازاڕکردن لە بەغدا.',
    rating: 4.6,
    reviewCount: 4500,
    isVerified: true,
    isFeatured: true,
    tags: ['shopping', 'brands', 'cinema'],
    priceRange: 3,
    openHours: '10:00 AM - 11:00 PM'
  },
  {
    id: '17',
    name: 'Erbil International Airport',
    nameAr: 'مطار أربيل الدولي',
    nameKu: 'فڕۆکەخانەی نێودەوڵەتی هەولێر',
    category: 'services',
    governorate: 'Erbil',
    city: 'Erbil',
    address: 'Erbil, Iraq',
    description: 'The main international gateway to the Kurdistan Region.',
    descriptionAr: 'البوابة الدولية الرئيسية لإقليم كوردستان.',
    descriptionKu: 'سەرەکیترین دەروازەی نێودەوڵەتی بۆ هەرێمی کوردستان.',
    rating: 4.4,
    reviewCount: 1500,
    isVerified: true,
    isFeatured: false,
    tags: ['airport', 'travel', 'transport'],
    priceRange: 3,
    openHours: '24/7'
  },
  {
    id: '18',
    name: 'Basra Sports City',
    nameAr: 'مدينة البصرة الرياضية',
    nameKu: 'شاری وەرزشی بەسرە',
    category: 'sports',
    governorate: 'Basra',
    city: 'Basra',
    address: 'Basra, Iraq',
    description: 'The largest sports complex in Iraq, featuring a 65,000-seat stadium.',
    descriptionAr: 'أكبر مجمع رياضي في العراق، يضم ملعباً يتسع لـ 65,000 متفرج.',
    descriptionKu: 'گەورەترین کۆمەڵگەی وەرزشی لە عێراق، کە یاریگایەکی ٦٥ هەزار کەسی لەخۆدەگرێت.',
    rating: 4.8,
    reviewCount: 2000,
    isVerified: true,
    isFeatured: true,
    tags: ['stadium', 'football', 'sports'],
    priceRange: 2,
    openHours: 'Depends on events'
  },
  {
    id: '19',
    name: 'Al-Mustansiriya University',
    nameAr: 'الجامعة المستنصرية',
    nameKu: 'زانکۆی موستەنسریە',
    category: 'education',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Al-Rusafa, Baghdad',
    description: 'Historic university named after the medieval Mustansiriya Madrasah.',
    descriptionAr: 'جامعة تاريخية سميت على اسم المدرسة المستنصرية في العصور الوسطى.',
    descriptionKu: 'زانکۆیەکی مێژوویی کە بە ناوی مەدرەسەی موستەنسریەی سەدەکانی ناوەڕاستەوە ناونراوە.',
    rating: 4.3,
    reviewCount: 400,
    isVerified: true,
    isFeatured: false,
    tags: ['university', 'education', 'historic'],
    priceRange: 1,
    openHours: '8:00 AM - 3:00 PM'
  },
  {
    id: '20',
    name: 'Majidi Mall Erbil',
    nameAr: 'مجيدي مول أربيل',
    nameKu: 'مەجیدی مۆڵ هەولێر',
    category: 'shopping',
    governorate: 'Erbil',
    city: 'Erbil',
    address: 'Koya Road, Erbil',
    description: 'Large shopping mall with a variety of local and international stores.',
    descriptionAr: 'مول تسوق كبير مع مجموعة متنوعة من المتاجر المحلية والعالمية.',
    descriptionKu: 'مۆڵێکی گەورەی بازاڕکردن بە جۆرەها فرۆشگای ناوخۆیی و نێودەوڵەتی.',
    rating: 4.5,
    reviewCount: 2800,
    isVerified: true,
    isFeatured: false,
    tags: ['shopping', 'hypermarket', 'food'],
    priceRange: 3,
    openHours: '9:00 AM - 11:00 PM'
  },
  {
    id: '21',
    name: 'Slemani Museum',
    nameAr: 'متحف السليمانية',
    nameKu: 'مۆزەخانەی سلێمانی',
    category: 'entertainment',
    governorate: 'Sulaymaniyah',
    city: 'Sulaymaniyah',
    address: 'Salim Street, Sulaymaniyah',
    description: 'The second largest museum in Iraq, housing artifacts from various periods.',
    descriptionAr: 'ثاني أكبر متحف في العراق، يضم قطعاً أثرية من فترات مختلفة.',
    descriptionKu: 'دووەم گەورەترین مۆزەخانە لە عێراق، کە شوێنەواری سەردەمە جیاوازەکانی تێدایە.',
    rating: 4.6,
    reviewCount: 700,
    isVerified: true,
    isFeatured: false,
    tags: ['museum', 'historic', 'culture'],
    priceRange: 1,
    openHours: '9:00 AM - 2:00 PM'
  },
  {
    id: '22',
    name: 'Al-Kindi General Hospital',
    nameAr: 'مستشفى الكندي العام',
    nameKu: 'نەخۆشخانەی گشتی ئەلکیندی',
    category: 'hospitals',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Al-Nahda, Baghdad',
    description: 'Major public hospital providing a wide range of medical services.',
    descriptionAr: 'مستشفى حكومي رئيسي يقدم مجموعة واسعة من الخدمات الطبية.',
    descriptionKu: 'نەخۆشخانەیەکی گشتی سەرەکی کە کۆمەڵێک خزمەتگوزاری پزیشکی بەرفراوان پێشکەش دەکات.',
    rating: 3.8,
    reviewCount: 300,
    isVerified: true,
    isFeatured: false,
    tags: ['hospital', 'public', 'medical'],
    priceRange: 1,
    openHours: '24/7'
  },
  {
    id: '23',
    name: 'Erbil Citadel',
    nameAr: 'قلعة أربيل',
    nameKu: 'قەڵای هەولێر',
    category: 'entertainment',
    governorate: 'Erbil',
    city: 'Erbil',
    address: 'City Center, Erbil',
    description: 'UNESCO World Heritage site and one of the oldest continuously inhabited places on Earth.',
    descriptionAr: 'موقع تراث عالمي لليونسكو وواحد من أقدم الأماكن المأهولة باستمرار على وجه الأرض.',
    descriptionKu: 'شوێنەواری کەلەپووری جیهانی یونسکۆ و یەکێک لە کۆنترین شوێنە نیشتەجێبووە بەردەوامەکانی سەر زەوی.',
    rating: 4.9,
    reviewCount: 5000,
    isVerified: true,
    isFeatured: true,
    tags: ['historic', 'landmark', 'unesco'],
    priceRange: 1,
    openHours: '9:00 AM - 6:00 PM'
  },
  {
    id: '24',
    name: 'Basra Times Square',
    nameAr: 'تايمز سكوير البصرة',
    nameKu: 'تایمز سکوێری بەسرە',
    category: 'shopping',
    governorate: 'Basra',
    city: 'Basra',
    address: 'Al-Jazaer Street, Basra',
    description: 'Modern shopping mall with international brands and a large food court.',
    descriptionAr: 'مول تسوق حديث مع علامات تجارية عالمية وساحة طعام كبيرة.',
    descriptionKu: 'مۆڵێکی بازاڕکردنی مۆدێرن بە براندە نێودەوڵەتییەکان و گۆڕەپانی خواردنی گەورە.',
    rating: 4.5,
    reviewCount: 2200,
    isVerified: true,
    isFeatured: true,
    tags: ['shopping', 'brands', 'food'],
    priceRange: 3,
    openHours: '10:00 AM - 11:00 PM'
  },
  {
    id: '25',
    name: 'University of Mosul',
    nameAr: 'جامعة الموصل',
    nameKu: 'زانکۆی مووسڵ',
    category: 'education',
    governorate: 'Nineveh',
    city: 'Mosul',
    address: 'Mosul, Iraq',
    description: 'One of the largest educational and research centers in the Middle East.',
    descriptionAr: 'واحد من أكبر المراكز التعليمية والبحثية في الشرق الأوسط.',
    descriptionKu: 'یەکێک لە گەورەترین ناوەندەکانی پەروەردە و توێژینەوە لە ڕۆژهەڵاتی ناوەڕاست.',
    rating: 4.4,
    reviewCount: 600,
    isVerified: true,
    isFeatured: false,
    tags: ['university', 'education', 'research'],
    priceRange: 1,
    openHours: '8:00 AM - 3:00 PM'
  },
  {
    id: '26',
    name: 'Sami Abdulrahman Park',
    nameAr: 'منتزه سامي عبد الرحمن',
    nameKu: 'پارکی سامی عەبدولڕەحمان',
    category: 'entertainment',
    governorate: 'Erbil',
    city: 'Erbil',
    address: '60m Road, Erbil',
    description: 'The largest park in Iraq, built on a former military base.',
    descriptionAr: 'أكبر منتزه في العراق، بني على قاعدة عسكرية سابقة.',
    descriptionKu: 'گەورەترین پارک لە عێراق، لەسەر بنکەیەکی سەربازی پێشوو دروستکراوە.',
    rating: 4.7,
    reviewCount: 4000,
    isVerified: true,
    isFeatured: true,
    tags: ['park', 'nature', 'family'],
    priceRange: 1,
    openHours: '6:00 AM - 12:00 AM'
  },
  {
    id: '27',
    name: 'Al-Yarmouk Hospital',
    nameAr: 'مستشفى اليرموك',
    nameKu: 'نەخۆشخانەی یەرمووک',
    category: 'hospitals',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Al-Yarmouk, Baghdad',
    description: 'Large teaching hospital in the heart of Baghdad.',
    descriptionAr: 'مستشفى تعليمي كبير في قلب بغداد.',
    descriptionKu: 'نەخۆشخانەیەکی فێرکاری گەورە لە دڵی بەغدا.',
    rating: 3.5,
    reviewCount: 250,
    isVerified: true,
    isFeatured: false,
    tags: ['hospital', 'teaching', 'medical'],
    priceRange: 1,
    openHours: '24/7'
  },
  {
    id: '28',
    name: 'Karbala International Stadium',
    nameAr: 'ملعب كربلاء الدولي',
    nameKu: 'یاریگای نێودەوڵەتی کەربەلا',
    category: 'sports',
    governorate: 'Karbala',
    city: 'Karbala',
    address: 'Karbala, Iraq',
    description: 'Modern football stadium with a capacity of 30,000.',
    descriptionAr: 'ملعب كرة قدم حديث يتسع لـ 30,000 متفرج.',
    descriptionKu: 'یاریگایەکی مۆدێرن بۆ تۆپی پێ کە جێگای ٣٠ هەزار کەس دەبێتەوە.',
    rating: 4.6,
    reviewCount: 1200,
    isVerified: true,
    isFeatured: false,
    tags: ['stadium', 'football', 'sports'],
    priceRange: 2,
    openHours: 'Depends on events'
  },
  {
    id: '29',
    name: 'Najaf City Mall',
    nameAr: 'نجف سيتي مول',
    nameKu: 'نەجەف سیتی مۆڵ',
    category: 'shopping',
    governorate: 'Najaf',
    city: 'Najaf',
    address: 'Najaf, Iraq',
    description: 'Premier shopping mall in the holy city of Najaf.',
    descriptionAr: 'مول التسوق الأول في مدينة النجف المقدسة.',
    descriptionKu: 'مۆڵی یەکەمی بازاڕکردن لە شاری پیرۆزی نەجەف.',
    rating: 4.4,
    reviewCount: 1500,
    isVerified: true,
    isFeatured: false,
    tags: ['shopping', 'family', 'food'],
    priceRange: 3,
    openHours: '10:00 AM - 11:00 PM'
  },
  {
    id: '30',
    name: 'Tahrir Square',
    nameAr: 'ساحة التحرير',
    nameKu: 'مەیدانی تەحریر',
    category: 'entertainment',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Al-Rusafa, Baghdad',
    description: 'The most famous square in Baghdad, known for its Freedom Monument.',
    descriptionAr: 'أشهر ساحة في بغداد، تشتهر بنصب الحرية.',
    descriptionKu: 'بەناوبانگترین مەیدانی بەغدا، کە بە مۆنۆمێنتی ئازادی ناسراوە.',
    rating: 4.8,
    reviewCount: 5000,
    isVerified: true,
    isFeatured: true,
    tags: ['square', 'historic', 'landmark'],
    priceRange: 1,
    openHours: '24/7'
  }
];

export const MOCK_REVIEWS: Review[] = [
  { id: 'r1', businessId: '1', authorName: 'Ahmed Ali', rating: 5, comment: 'Amazing stay! The staff was very professional.', date: '2024-03-01', helpful: 12 },
  { id: 'r2', businessId: '2', authorName: 'Sara Hassan', rating: 4, comment: 'The Masgouf was delicious, but the service was a bit slow.', date: '2024-02-15', helpful: 8 },
  { id: 'r3', businessId: '3', authorName: 'Mohammed Jassim', rating: 5, comment: 'Great mall with everything you need.', date: '2024-03-05', helpful: 20 },
  { id: 'r4', businessId: '4', authorName: 'Zainab Abbas', rating: 4, comment: 'Lovely atmosphere and great coffee.', date: '2024-02-28', helpful: 5 },
  { id: 'r5', businessId: '5', authorName: 'Mustafa Karim', rating: 5, comment: 'Excellent medical care and very clean facility.', date: '2024-03-10', helpful: 15 },
  { id: 'r6', businessId: '9', authorName: 'Layla Omar', rating: 5, comment: 'Best shopping experience in Erbil!', date: '2024-03-12', helpful: 10 },
  { id: 'r7', businessId: '11', authorName: 'Hassan Mahmoud', rating: 5, comment: 'The view from the revolving restaurant is breathtaking.', date: '2024-03-08', helpful: 18 },
  { id: 'r8', businessId: '23', authorName: 'Noor Al-Huda', rating: 5, comment: 'A must-visit historical site. Truly impressive.', date: '2024-03-15', helpful: 25 },
  { id: 'r9', businessId: '26', authorName: 'Ali Reza', rating: 4, comment: 'Great place for a family walk. Very spacious.', date: '2024-03-14', helpful: 7 },
  { id: 'r10', businessId: '30', authorName: 'Fatima Zahra', rating: 5, comment: 'The heart of Baghdad. Full of energy and history.', date: '2024-03-16', helpful: 30 },
  { id: 'r11', businessId: '1', authorName: 'Omar Faruk', rating: 4, comment: 'Very comfortable rooms, but a bit expensive.', date: '2024-02-20', helpful: 3 },
  { id: 'r12', businessId: '2', authorName: 'Muna Ahmed', rating: 5, comment: 'Authentic taste. Highly recommended for visitors.', date: '2024-02-10', helpful: 11 },
  { id: 'r13', businessId: '7', authorName: 'Yousif Khalid', rating: 4, comment: 'Good variety of shops, but gets very crowded on weekends.', date: '2024-03-02', helpful: 6 },
  { id: 'r14', businessId: '10', authorName: 'Dina Ali', rating: 4, comment: 'Kids loved the rides! Great family day out.', date: '2024-03-04', helpful: 9 },
  { id: 'r15', businessId: '18', authorName: 'Karrar Jassim', rating: 5, comment: 'World-class stadium. Proud to have this in Basra.', date: '2024-03-11', helpful: 22 }
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    searchPlaceholder: 'Search businesses, events...',
    allCategories: 'All Categories',
    featured: 'Featured',
    viewDetails: 'View Details',
    verified: 'Verified',
    rating: 'Rating',
    reviews: 'Reviews',
    browseAll: 'Browse All',
    noResults: 'No results found',
    tryDifferent: 'Try different filters',
    back: 'Back',
    home: 'Home',
    browse: 'Browse',
    search: 'Search',
    profile: 'Profile',
    directions: 'Directions',
    call: 'Call',
    share: 'Share',
    loading: 'Loading...',
    aiCurated: 'AI-Curated',
    generateEvents: 'Generate Events',
    discoverIraq: 'Discover Iraq',
    findBest: 'Find the Best',
    businessesEvents: 'Businesses & Events',
    acrossIraq: 'Across Iraq',
    topRated: 'Top Rated',
    aiEvents: 'AI Events',
    thisWeek: 'This Week',
    showingResults: 'Showing results',
    filters: 'Filters',
    clearAll: 'Clear All',
    sortBy: 'Sort By',
    highestRated: 'Highest Rated',
    az: 'A-Z',
    newest: 'Newest',
    mostReviewed: 'Most Reviewed',
    governorate: 'Governorate',
    city: 'City',
    category: 'Category',
    allGovernorates: 'All Governorates',
    exploreByGov: 'Explore by Governorate',
    browseByCategory: 'Browse by Category',
    featuredInIraq: 'Featured in Iraq',
    highestRatedSub: 'Highest rated across all cities',
    aiCuratedEvents: 'AI-Curated Events',
    aiEventsSub: 'Generated for Iraq this week',
    browseByCity: 'Browse by city:',
    statsRow: '500+ Businesses · 18 Governorates · 3 Languages',
    more: 'More',
    places: 'places',
    businesses: 'businesses',
    tryArabicKurdish: 'Try searching for categories like "Restaurants" or cities like "Erbil". You can also search in Arabic or Kurdish.',
    phone: 'Phone',
    address: 'Address',
    hours: 'Hours',
    moreIn: 'More in',
    comingSoon: 'Coming soon'
  },
  ar: {
    searchPlaceholder: 'ابحث عن أعمال، فعاليات...',
    allCategories: 'جميع الفئات',
    featured: 'مميز',
    viewDetails: 'عرض التفاصيل',
    verified: 'موثق',
    rating: 'التقييم',
    reviews: 'مراجعات',
    browseAll: 'تصفح الكل',
    noResults: 'لم يتم العثور على نتائج',
    tryDifferent: 'جرب فلاتر مختلفة',
    back: 'رجوع',
    home: 'الرئيسية',
    browse: 'تصفح',
    search: 'بحث',
    profile: 'الملف الشخصي',
    directions: 'الاتجاهات',
    call: 'اتصال',
    share: 'مشاركة',
    loading: 'جاري التحميل...',
    aiCurated: 'منسق بالذكاء الاصطناعي',
    generateEvents: 'توليد فعاليات',
    discoverIraq: 'اكتشف العراق',
    findBest: 'جد الأفضل',
    businessesEvents: 'الأعمال والفعاليات',
    acrossIraq: 'في جميع أنحاء العراق',
    topRated: 'الأعلى تقييماً',
    aiEvents: 'فعاليات الذكاء الاصطناعي',
    thisWeek: 'هذا الأسبوع',
    showingResults: 'عرض النتائج',
    filters: 'الفلاتر',
    clearAll: 'مسح الكل',
    sortBy: 'ترتيب حسب',
    highestRated: 'الأعلى تقييماً',
    az: 'أ-ي',
    newest: 'الأحدث',
    mostReviewed: 'الأكثر مراجعة',
    governorate: 'المحافظة',
    city: 'المدينة',
    category: 'الفئة',
    allGovernorates: 'جميع المحافظات',
    exploreByGov: 'استكشف حسب المحافظة',
    browseByCategory: 'تصفح حسب الفئة',
    featuredInIraq: 'مميز في العراق',
    highestRatedSub: 'الأعلى تقييماً في جميع المدن',
    aiCuratedEvents: 'فعاليات منسقة بالذكاء الاصطناعي',
    aiEventsSub: 'تم توليدها للعراق هذا الأسبوع',
    browseByCity: 'تصفح حسب المدينة:',
    statsRow: '500+ عمل تجاري · 18 محافظة · 3 لغات',
    more: 'المزيد',
    places: 'أماكن',
    businesses: 'أعمال',
    tryArabicKurdish: 'جرب البحث عن فئات مثل "مطاعم" أو مدن مثل "أربيل". يمكنك أيضاً البحث باللغة العربية أو الكردية.',
    phone: 'الهاتف',
    address: 'العنوان',
    hours: 'ساعات العمل',
    moreIn: 'المزيد في',
    comingSoon: 'قريباً'
  },
  ku: {
    searchPlaceholder: 'گەڕان بۆ کارەکان، چالاکییەکان...',
    allCategories: 'هەموو جۆرەکان',
    featured: 'دیاریکراو',
    viewDetails: 'بینینی وردەکارییەکان',
    verified: 'پەسەندکراو',
    rating: 'پلەبەندی',
    reviews: 'پێداچوونەوەکان',
    browseAll: 'بینینی هەمووی',
    noResults: 'هیچ ئەنجامێک نەدۆزرایەوە',
    tryDifferent: 'فلتەری جیاواز تاقی بکەرەوە',
    back: 'گەڕانەوە',
    home: 'سەرەکی',
    browse: 'گەڕان',
    search: 'گەڕان',
    profile: 'پڕۆفایل',
    directions: 'ئاراستەکان',
    call: 'پەیوەندی',
    share: 'هاوبەشکردن',
    loading: 'بارکردن...',
    aiCurated: 'ڕێکخراو بە ژیری دەستکرد',
    generateEvents: 'دروستکردنی چالاکییەکان',
    discoverIraq: 'عێراق بدۆزەرەوە',
    findBest: 'باشترین بدۆزەرەوە',
    businessesEvents: 'کارەکان و چالاکییەکان',
    acrossIraq: 'لە سەرانسەری عێراق',
    topRated: 'بەرزترین پلەبەندی',
    aiEvents: 'چالاکییەکانی ژیری دەستکرد',
    thisWeek: 'ئەم هەفتەیە',
    showingResults: 'پیشاندانی ئەنجامەکان',
    filters: 'فلتەرەکان',
    clearAll: 'سڕینەوەی هەموو',
    sortBy: 'ڕیزکردن بەپێی',
    highestRated: 'بەرزترین پلەبەندی',
    az: 'ئ-ی',
    newest: 'نوێترین',
    mostReviewed: 'زۆرترین پێداچوونەوە',
    governorate: 'پارێزگا',
    city: 'شار',
    category: 'جۆر',
    allGovernorates: 'هەموو پارێزگاکان',
    exploreByGov: 'گەڕان بەپێی پارێزگا',
    browseByCategory: 'گەڕان بەپێی جۆر',
    featuredInIraq: 'دیاریکراو لە عێراق',
    highestRatedSub: 'بەرزترین پلەبەندی لە هەموو شارەکان',
    aiCuratedEvents: 'چالاکییە ڕێکخراوەکان بە ژیری دەستکرد',
    aiEventsSub: 'دروستکراوە بۆ عێراق ئەم هەفتەیە',
    browseByCity: 'گەڕان بەپێی شار:',
    statsRow: '500+ کار · 18 پارێزگا · 3 زمان',
    more: 'زیاتر',
    places: 'شوێنەکان',
    businesses: 'کارەکان',
    tryArabicKurdish: 'هەوڵ بدە بۆ گەڕان بۆ جۆرەکانی وەک "چێشتخانەکان" یان شارەکانی وەک "هەولێر". هەروەها دەتوانیت بە زمانی عەرەبی یان کوردی بگەڕێیت.',
    phone: 'تەلەفۆن',
    address: 'ناونیشان',
    hours: 'کاتژمێرەکان',
    moreIn: 'زیاتر لە',
    comingSoon: 'بەمنزیکانە'
  }
};
