import { CategoryInfo, CityInfo, Business, Review, Language } from './types';

export const CATEGORIES: CategoryInfo[] = [
  { id: 'restaurants', labelEn: 'Restaurants', labelAr: 'مطاعم', labelKu: 'چێشتخانەکان', emoji: '🍽️' },
  { id: 'cafes', labelEn: 'Cafes', labelAr: 'مقاهي', labelKu: 'کافێکان', emoji: '☕' },
  { id: 'hotels', labelEn: 'Hotels', labelAr: 'فنادق', labelKu: 'هوتێلەکان', emoji: '🏨' },
  { id: 'hospitals', labelEn: 'Hospitals', labelAr: 'مستشفيات', labelKu: 'نەخۆشخانەکان', emoji: '🏥' },
  { id: 'pharmacies', labelEn: 'Pharmacies', labelAr: 'صيدليات', labelKu: 'دەرمانخانەکان', emoji: '💊' },
  { id: 'shopping', labelEn: 'Shopping', labelAr: 'تسوق', labelKu: 'بازاڕکردن', emoji: '🛍️' },
  { id: 'education', labelEn: 'Education', labelAr: 'تعليم', labelKu: 'پەروەردە', emoji: '🎓' },
  { id: 'beauty', labelEn: 'Beauty', labelAr: 'تجميل', labelKu: 'جوانی', emoji: '💇' },
  { id: 'automotive', labelEn: 'Automotive', labelAr: 'سيارات', labelKu: 'ئۆتۆمبێل', emoji: '🚗' },
  { id: 'entertainment', labelEn: 'Entertainment', labelAr: 'ترفيه', labelKu: 'کات بەسەربردن', emoji: '🎭' },
  { id: 'sports', labelEn: 'Sports', labelAr: 'رياضة', labelKu: 'وەرزش', emoji: '⚽' },
  { id: 'services', labelEn: 'Services', labelAr: 'خدمات', labelKu: 'خزمەتگوزارییەکان', emoji: '🔧' },
];

export const GOVERNORATES = [
  'Baghdad', 'Basra', 'Nineveh', 'Erbil', 'Sulaymaniyah',
  'Duhok', 'Kirkuk', 'Anbar', 'Diyala', 'Babil', 'Karbala',
  'Najaf', 'Wasit', 'Maysan', 'Dhi Qar', 'Muthanna',
  'Qadisiyyah', 'Saladin'
];

export const CITIES: CityInfo[] = [
  { id: 'baghdad', nameEn: 'Baghdad', nameAr: 'بغداد', nameKu: 'بەغدا', governorate: 'Baghdad', emoji: '🕌' },
  { id: 'basra', nameEn: 'Basra', nameAr: 'البصرة', nameKu: 'بەسرە', governorate: 'Basra', emoji: '⚓' },
  { id: 'mosul', nameEn: 'Mosul', nameAr: 'الموصل', nameKu: 'مووسڵ', governorate: 'Nineveh', emoji: '🌉' },
  { id: 'erbil', nameEn: 'Erbil', nameAr: 'أربيل', nameKu: 'هەولێر', governorate: 'Erbil', emoji: '🏰' },
  { id: 'sulaymaniyah', nameEn: 'Sulaymaniyah', nameAr: 'السليمانية', nameKu: 'سلێمانی', governorate: 'Sulaymaniyah', emoji: '⛰️' },
  { id: 'duhok', nameEn: 'Duhok', nameAr: 'دهوك', nameKu: 'دهۆک', governorate: 'Duhok', emoji: '🏞️' },
  { id: 'kirkuk', nameEn: 'Kirkuk', nameAr: 'كركوك', nameKu: 'کەرکووک', governorate: 'Kirkuk', emoji: '🔥' },
  { id: 'karbala', nameEn: 'Karbala', nameAr: 'كربلاء', nameKu: 'کەربەلا', governorate: 'Karbala', emoji: '🕌' },
  { id: 'najaf', nameEn: 'Najaf', nameAr: 'النجف', nameKu: 'نەجەف', governorate: 'Najaf', emoji: '🕌' },
  { id: 'zakho', nameEn: 'Zakho', nameAr: 'زاخو', nameKu: 'زاخۆ', governorate: 'Duhok', emoji: '🌉' },
];

export const MOCK_BUSINESSES: Business[] = [
  {
    id: '1',
    name: 'Rotana Erbil Hotel',
    nameAr: 'فندق روتانا أربيل',
    nameKu: 'هوتێلی رۆتانا هەولێر',
    category: 'hotels',
    governorate: 'Erbil',
    city: 'Erbil',
    address: 'Gulan Street, Erbil',
    phone: '+964 66 210 5555',
    description: 'A luxury 5-star hotel located in the heart of Erbil, offering world-class amenities and service.',
    descriptionAr: 'فندق فاخر 5 نجوم يقع في قلب أربيل، يقدم مرافق وخدمات عالمية المستوى.',
    descriptionKu: 'هوتێلێکی لوکس ٥ ئەستێرە کە لە دڵی هەولێر هەڵکەوتووە، ئاسانکاری و خزمەتگوزاری ئاستی جیهانی پێشکەش دەکات.',
    rating: 4.8,
    reviewCount: 1250,
    isVerified: true,
    isFeatured: true,
    tags: ['luxury', 'pool', 'spa', 'business'],
    priceRange: 4,
    openHours: '24/7'
  },
  {
    id: '2',
    name: 'Al-Rasheed Restaurant',
    nameAr: 'مطعم الرشيد',
    nameKu: 'چێشتخانەی ڕەشید',
    category: 'restaurants',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'Al-Mansour, Baghdad',
    phone: '+964 780 123 4567',
    description: 'Traditional Iraqi cuisine served in an elegant atmosphere. Famous for Masgouf.',
    descriptionAr: 'مأكولات عراقية تقليدية تقدم في أجواء راقية. مشهور بالمسكوف.',
    descriptionKu: 'خواردنی نەریتی عێراقی کە لە کەشێکی ڕاقیدا پێشکەش دەکرێت. بە مەسگوف بەناوبانگە.',
    rating: 4.5,
    reviewCount: 850,
    isVerified: true,
    isFeatured: true,
    tags: ['traditional', 'masgouf', 'family'],
    priceRange: 3,
    openHours: '12:00 PM - 12:00 AM'
  },
  {
    id: '3',
    name: 'Kurdistan Mall',
    nameAr: 'كوردستان مول',
    nameKu: 'کوردستان مۆڵ',
    category: 'shopping',
    governorate: 'Erbil',
    city: 'Erbil',
    address: '100m Road, Erbil',
    description: 'One of the largest shopping malls in Erbil with international brands and a food court.',
    descriptionAr: 'واحد من أكبر مراكز التسوق في أربيل مع علامات تجارية عالمية وساحة طعام.',
    descriptionKu: 'یەکێک لە گەورەترین مۆڵەکانی بازاڕکردن لە هەولێر بە براندە نێودەوڵەتییەکان و گۆڕەپانی خواردن.',
    rating: 4.6,
    reviewCount: 2100,
    isVerified: true,
    isFeatured: true,
    tags: ['shopping', 'brands', 'cinema'],
    priceRange: 3,
    openHours: '10:00 AM - 11:00 PM'
  },
  {
    id: '4',
    name: 'Divan Cafe',
    nameAr: 'ديوان كافيه',
    nameKu: 'دیوان کافێ',
    category: 'cafes',
    governorate: 'Sulaymaniyah',
    city: 'Sulaymaniyah',
    address: 'Salim Street, Sulaymaniyah',
    description: 'Cozy cafe with a great selection of coffee and desserts. Perfect for studying or meetings.',
    descriptionAr: 'مقهى مريح مع مجموعة رائعة من القهوة والحلويات. مثالي للدراسة أو الاجتماعات.',
    descriptionKu: 'کافێیەکی ئارام بە هەڵبژاردەیەکی زۆری قاوە و شیرینی. گونجاوە بۆ خوێندن یان کۆبوونەوە.',
    rating: 4.7,
    reviewCount: 420,
    isVerified: false,
    isFeatured: false,
    tags: ['coffee', 'wifi', 'desserts'],
    priceRange: 2,
    openHours: '8:00 AM - 12:00 AM'
  },
  {
    id: '5',
    name: 'Ibn Sina Hospital',
    nameAr: 'مستشفى ابن سينا',
    nameKu: 'نەخۆشخانەی ئیبن سینا',
    category: 'hospitals',
    governorate: 'Baghdad',
    city: 'Baghdad',
    address: 'International Zone, Baghdad',
    description: 'A leading medical facility providing specialized healthcare services.',
    descriptionAr: 'منشأة طبية رائدة تقدم خدمات رعاية صحية متخصصة.',
    descriptionKu: 'دامەزراوەیەکی پزیشکی پێشەنگ کە خزمەتگوزارییە تەندروستییە پسپۆڕییەکان پێشکەش دەکات.',
    rating: 4.9,
    reviewCount: 150,
    isVerified: true,
    isFeatured: false,
    tags: ['medical', 'emergency', 'specialized'],
    priceRange: 3,
    openHours: '24/7'
  },
  // Adding more mock data to reach 30+
  ...Array.from({ length: 25 }).map((_, i) => ({
    id: `mock-${i}`,
    name: `Business ${i + 6}`,
    nameAr: `عمل تجاري ${i + 6}`,
    nameKu: `کار ${i + 6}`,
    category: CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)].id,
    governorate: GOVERNORATES[Math.floor(Math.random() * GOVERNORATES.length)],
    city: CITIES[Math.floor(Math.random() * CITIES.length)].nameEn,
    address: `Street ${i + 6}, Iraq`,
    description: `Description for business ${i + 6}. Providing quality services across Iraq.`,
    descriptionAr: `وصف للعمل التجاري ${i + 6}. تقديم خدمات عالية الجودة في جميع أنحاء العراق.`,
    descriptionKu: `وەسف بۆ کار ${i + 6}. پێشکەشکردنی خزمەتگوزاری کوالێتی لە سەرانسەری عێراق.`,
    rating: 3.5 + Math.random() * 1.5,
    reviewCount: Math.floor(Math.random() * 500),
    isVerified: Math.random() > 0.5,
    isFeatured: Math.random() > 0.8,
    tags: ['service', 'quality', 'iraq'],
    priceRange: (Math.floor(Math.random() * 4) + 1) as 1 | 2 | 3 | 4,
    openHours: '9:00 AM - 9:00 PM'
  }))
];

export const MOCK_REVIEWS: Review[] = [
  { id: 'r1', businessId: '1', authorName: 'Ahmed Ali', rating: 5, comment: 'Amazing stay! The staff was very professional.', date: '2024-03-01', helpful: 12 },
  { id: 'r2', businessId: '2', authorName: 'Sara Hassan', rating: 4, comment: 'The Masgouf was delicious, but the service was a bit slow.', date: '2024-02-15', helpful: 8 },
  { id: 'r3', businessId: '3', authorName: 'Mohammed Jassim', rating: 5, comment: 'Great mall with everything you need.', date: '2024-03-05', helpful: 20 },
  ...Array.from({ length: 12 }).map((_, i) => ({
    id: `rev-${i}`,
    businessId: String(Math.floor(Math.random() * 5) + 1),
    authorName: `Reviewer ${i + 4}`,
    rating: Math.floor(Math.random() * 3) + 3,
    comment: 'Great experience, highly recommended!',
    date: '2024-01-20',
    helpful: Math.floor(Math.random() * 10)
  }))
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    searchPlaceholder: 'Search businesses, events...',
    allCategories: 'All Categories',
    featured: 'Featured',
    viewDetails: 'View Details',
    verified: 'Verified',
    rating: 'Rating',
    reviews: 'Reviews',
    browseAll: 'Browse All',
    noResults: 'No results found',
    tryDifferent: 'Try different filters',
    back: 'Back',
    home: 'Home',
    browse: 'Browse',
    search: 'Search',
    profile: 'Profile',
    directions: 'Directions',
    call: 'Call',
    share: 'Share',
    loading: 'Loading...',
    aiCurated: 'AI-Curated',
    generateEvents: 'Generate Events',
    discoverIraq: 'Discover Iraq',
    findBest: 'Find the Best',
    businessesEvents: 'Businesses & Events',
    acrossIraq: 'Across Iraq',
    topRated: 'Top Rated',
    aiEvents: 'AI Events',
    thisWeek: 'This Week',
    showingResults: 'Showing results',
    filters: 'Filters',
    clearAll: 'Clear All',
    sortBy: 'Sort By',
    highestRated: 'Highest Rated',
    az: 'A-Z',
    newest: 'Newest',
    mostReviewed: 'Most Reviewed',
    governorate: 'Governorate',
    city: 'City',
    category: 'Category',
    allGovernorates: 'All Governorates',
    exploreByGov: 'Explore by Governorate',
    browseByCategory: 'Browse by Category',
    featuredInIraq: 'Featured in Iraq',
    highestRatedSub: 'Highest rated across all cities',
    aiCuratedEvents: 'AI-Curated Events',
    aiEventsSub: 'Generated for Iraq this week',
    browseByCity: 'Browse by city:',
    statsRow: '500+ Businesses · 18 Governorates · 3 Languages'
  },
  ar: {
    searchPlaceholder: 'ابحث عن أعمال، فعاليات...',
    allCategories: 'جميع الفئات',
    featured: 'مميز',
    viewDetails: 'عرض التفاصيل',
    verified: 'موثق',
    rating: 'التقييم',
    reviews: 'مراجعات',
    browseAll: 'تصفح الكل',
    noResults: 'لم يتم العثور على نتائج',
    tryDifferent: 'جرب فلاتر مختلفة',
    back: 'رجوع',
    home: 'الرئيسية',
    browse: 'تصفح',
    search: 'بحث',
    profile: 'الملف الشخصي',
    directions: 'الاتجاهات',
    call: 'اتصال',
    share: 'مشاركة',
    loading: 'جاري التحميل...',
    aiCurated: 'منسق بالذكاء الاصطناعي',
    generateEvents: 'توليد فعاليات',
    discoverIraq: 'اكتشف العراق',
    findBest: 'جد الأفضل',
    businessesEvents: 'الأعمال والفعاليات',
    acrossIraq: 'في جميع أنحاء العراق',
    topRated: 'الأعلى تقييماً',
    aiEvents: 'فعاليات الذكاء الاصطناعي',
    thisWeek: 'هذا الأسبوع',
    showingResults: 'عرض النتائج',
    filters: 'الفلاتر',
    clearAll: 'مسح الكل',
    sortBy: 'ترتيب حسب',
    highestRated: 'الأعلى تقييماً',
    az: 'أ-ي',
    newest: 'الأحدث',
    mostReviewed: 'الأكثر مراجعة',
    governorate: 'المحافظة',
    city: 'المدينة',
    category: 'الفئة',
    allGovernorates: 'جميع المحافظات',
    exploreByGov: 'استكشف حسب المحافظة',
    browseByCategory: 'تصفح حسب الفئة',
    featuredInIraq: 'مميز في العراق',
    highestRatedSub: 'الأعلى تقييماً في جميع المدن',
    aiCuratedEvents: 'فعاليات منسقة بالذكاء الاصطناعي',
    aiEventsSub: 'تم توليدها للعراق هذا الأسبوع',
    browseByCity: 'تصفح حسب المدينة:',
    statsRow: '500+ عمل تجاري · 18 محافظة · 3 لغات'
  },
  ku: {
    searchPlaceholder: 'گەڕان بۆ کارەکان، چالاکییەکان...',
    allCategories: 'هەموو جۆرەکان',
    featured: 'دیاریکراو',
    viewDetails: 'بینینی وردەکارییەکان',
    verified: 'پەسەندکراو',
    rating: 'پلەبەندی',
    reviews: 'پێداچوونەوەکان',
    browseAll: 'بینینی هەمووی',
    noResults: 'هیچ ئەنجامێک نەدۆزرایەوە',
    tryDifferent: 'فلتەری جیاواز تاقی بکەرەوە',
    back: 'گەڕانەوە',
    home: 'سەرەکی',
    browse: 'گەڕان',
    search: 'گەڕان',
    profile: 'پڕۆفایل',
    directions: 'ئاراستەکان',
    call: 'پەیوەندی',
    share: 'هاوبەشکردن',
    loading: 'بارکردن...',
    aiCurated: 'ڕێکخراو بە ژیری دەستکرد',
    generateEvents: 'دروستکردنی چالاکییەکان',
    discoverIraq: 'عێراق بدۆزەرەوە',
    findBest: 'باشترین بدۆزەرەوە',
    businessesEvents: 'کارەکان و چالاکییەکان',
    acrossIraq: 'لە سەرانسەری عێراق',
    topRated: 'بەرزترین پلەبەندی',
    aiEvents: 'چالاکییەکانی ژیری دەستکرد',
    thisWeek: 'ئەم هەفتەیە',
    showingResults: 'پیشاندانی ئەنجامەکان',
    filters: 'فلتەرەکان',
    clearAll: 'سڕینەوەی هەموو',
    sortBy: 'ڕیزکردن بەپێی',
    highestRated: 'بەرزترین پلەبەندی',
    az: 'ئ-ی',
    newest: 'نوێترین',
    mostReviewed: 'زۆرترین پێداچوونەوە',
    governorate: 'پارێزگا',
    city: 'شار',
    category: 'جۆر',
    allGovernorates: 'هەموو پارێزگاکان',
    exploreByGov: 'گەڕان بەپێی پارێزگا',
    browseByCategory: 'گەڕان بەپێی جۆر',
    featuredInIraq: 'دیاریکراو لە عێراق',
    highestRatedSub: 'بەرزترین پلەبەندی لە هەموو شارەکان',
    aiCuratedEvents: 'چالاکییە ڕێکخراوەکان بە ژیری دەستکرد',
    aiEventsSub: 'دروستکراوە بۆ عێراق ئەم هەفتەیە',
    browseByCity: 'گەڕان بەپێی شار:',
    statsRow: '500+ کار · 18 پارێزگا · 3 زمان'
  }
};
